In [197]:
import pandas as pd
import numpy as np
import re

In [198]:
# tabela = pd.read_excel()

In [199]:
import re

# Padrões com \d+ para representar qualquer número
#Padronizar os dias
def verificar_padrao(entry):
    text = str(entry)
    padroes = [
    r"^\d+\s*a\s*\d+$",
    r"^\d+\s*-\s*\d+$",
    r"^\d+\s*-\s*\d+\s*dias$",
    r"^de\s+\d+\s*a\s+\d+\s*dias$",
    r"^\d+\s*e\s*\d+\s*dias$",
    r"^acima\s+de\s+\d+\s*dias$",
    r"^superior\s+a\s+\d+$",
    r"^superior\s+\d+$",
    r"^>\s*\d+$",
    r"^até\s+\d+$",
    r"^até\s+\d+\s*dias$"
    ]
    text = text.lower().strip()
    return any(re.search(padrao, text) for padrao in padroes)

def verificar_padrao2(entry):
    text = str(entry).lower().strip()
    padroes = [
        r'(\d+)\s*-\s*(\d+)\s*dias?',                   # intervalo: 10 - 20 dias
        r'>\s*(\d+)\s*dias?',                           # > 120 dias
        r'<=\s*(\d+)\s*dias?'                           # <= 10 dias
    ]
    return any(re.search(p, text) for p in padroes)

def padronizar_string(texto):
    if not texto or not isinstance(texto, str):
        return None

    texto = texto.lower().strip()
    subtrair_se_comecar_em = {6, 16, 31, 61, 91, 121, 151, 181, 366, 721}

    padroes = [
        (r"^1-(\d+)", lambda m: f"0-{m.group(1)} dias"),

        (r"^de\s*(\d+)\s*a\s*(\d+)\s*dias?$", lambda m:
         f"{int(m.group(1)) - 1 if int(m.group(1)) in subtrair_se_comecar_em else m.group(1)}-{m.group(2)} dias"),

        (r"^(\d+)\s*(?:a|e|-)\s*(\d+)\s*dias?$", lambda m:
         f"{int(m.group(1)) - 1 if int(m.group(1)) in subtrair_se_comecar_em else m.group(1)}-{m.group(2)} dias"),

        (r"^(\d+)\s*(?:a|e|-)\s*(\d+)$", lambda m:
         f"{int(m.group(1)) - 1 if int(m.group(1)) in subtrair_se_comecar_em else m.group(1)}-{m.group(2)} dias"),

        (r"^até\s*(\d+)(?:\s*dias?)?$", lambda m: f"<= {m.group(1)} dias"),

        (r"^>\s*(\d+)$", lambda m: f"> {int(m.group(1))-1 if int(m.group(1)) == 121 else m.group(1)} dias"),

        (r"^(?:acima\s*de|superior(?:\s*a)?)\s*(\d+)(?:\s*dias?)?$", lambda m: f"> {int(m.group(1))-1 if int(m.group(1)) == 121 else m.group(1)} dias"),
    ]

    for padrao, formato in padroes:
        match = re.fullmatch(padrao, texto)
        if match:
            return formato(match)
    return None

In [200]:
def padronizar_colunas_dias(df):
    columns = pd.Series(df.columns)

    result = columns.apply(verificar_padrao)
    print(result)
    days_columns = columns[result]

    final = days_columns.apply(padronizar_string)

    columns[result] = final

    df.columns = columns

    return df

In [201]:
import yaml
def carregar_yaml(caminho_yaml):
    with open(caminho_yaml, 'r', encoding='utf-8') as f:
        dados = yaml.safe_load(f)

    return dados  # Retorna como dicionário: {coluna_final: [possibilidades]}

colunas_equivalentes = carregar_yaml("../YAMLs/colunas.YAML")
padroes_regex_col = carregar_yaml("../YAMLs/regex.YAML")

colunas_equivalentes

{'PL Total': ['Patrimônio Líquido Total', 'PL Total Classe (R$ mil)'],
 'PL Sênior': ['PL Senior', 'PL Senior ', 'PL Sênior '],
 'PL Mezanino': ['PL Subordinada Mezanino'],
 'PL Subordinada Jr': ['PL Subordinada Jr.',
  'PL Subordinada Jr:',
  'PL Subordinada Junior',
  'PL Subordinada Júnior'],
 'Carteira (Direitos Creditórios)': ['Carteira (Direiros Creditórios)',
  'Carteira Direitos Creditórios (Vlr Presente)',
  'Carteira Total (Direitos Creditórios)',
  'Direitos Creditórios',
  'Total Direitos Creditórios (R$ mil)'],
 'Quantidade de Cedentes': ['Qtidade Cedentes',
  'Quantidade Cedentes',
  '# cedentes'],
 'Quantidade de Sacados': ['Qtidade Sacados',
  'Quantidade Sacados',
  '# sacados'],
 'Caixa/Disponibilidades': ['Caixa+Disponibilidades'],
 'Taxa Média': ['TIR - Mês -  Carteira (Dir.Creditórios)',
  'Taxa Média Recebíveis Média ponderada',
  'Taxa Média a.m',
  'Taxa Média a.m (*)',
  'Taxa Média (a.m.)',
  'Taxa Ponderada de Cessão'],
 'Prazo Médio': ['Prazo Médio Carteira (Dir.Creditórios) D.U',
  'Prazo médio',
  'Prazo Médio Recebíveis Estoque (dias úteis)',
  'Prazo medio',
  'Prazo médio aquisição no mês',
  'Prazo medio (em dias corridos)',
  'Prazo medio (dia útil)',
  'Prazo médio  (dias úteis)'],
 'Ticket Médio': ['Ticket Médio (Valor Presente)'],
 'Retorno Cota Subordinada': ['Rentabilidade Subordinada',
  'Retorno Cota Subordinada - Rentabilidade'],
 'Cheques': ['Cheque',
  'Cheque (Vlr Presente-PDD)',
  'Carteira (Cheques - Anima)'],
 'Duplicata': ['Duplicatas',
  'Duplicata (Vlr Presente-PDD)',
  'Carteira (Duplicatas - Anima)'],
 'Duplicata de Serviço Físico': ['Duplicata de Servico Fisico',
  'Duplicata de Serviço Físico',
  'Duplicata de Serviços'],
 'Contrato': ['Contrato Físico',
  'Contrato Fisico',
  'Contrato (Vlr Presente-PDD)'],
 'Nota Comercial': ['Nota Comercial '],
 'Confissão de Dívida': ['Confissao de Divida',
  'Confissão de Divida',
  'Confissão de Dívida'],
 'Nota Promissória': ['Nota Promissoria',
  'Nota Promissoria Fisica',
  'Nota Promissória (Vlr Presente-PDD)',
  'Promissoria',
  'Promissória'],
 'CCB': ['CCB PRE', 'CCB ', 'CCB (Vlr Presente-PDD)'],
 'Resgates Subordinada Jr.': ['Amortização e resgates Subordinada Jr.',
  'Captação/Resgate Subordinada Junior'],
 'Resgates Subordinada Mezanino': ['Amortização e resgates Mez',
  'Captação/Resgate Subordinada Mezanino'],
 'Resgates Sênior': ['Amortização e resgates Sênior',
  'Captação/Resgate Superiores/Sêniores'],
 'Vencidos Total': ['Vencidos Total (R$) (Vlr Presente-PDD)',
  'Vencidos Total (Base: Último Dia Útil do Mês)',
  'Vencidos Total (Singulare)',
  'Vencidos Total (sem WO)',
  'Vencidos',
  'Vencidos (1 até 120 dias)'],
 'PDD Total': ['PDD',
  'PDD Total (R$) (Vlr PDD)',
  'PDD Total Vencido (Base: Último Dia Útil do Mês)',
  'PDD Total (sem WO)'],
 'PDD À Vencer': ['PDD À Vencer (Devido efeito vagão)', 'PDD à Vencer'],
 'Liquidado Total(R$)': ['Total Liquidados',
  'Liquidados (R$)',
  'Liquidados Total',
  'Liquidados Normal ou Parcial (R$)',
  'Liquidados - Vencimento no Mês',
  'Volume Liquidado',
  'Volume liquidado'],
 'Liquidado Antecipadamente': ['Liquidado antecipadamente',
  'Liquidado antes do vencimento',
  'Antecipado',
  'Liquidados antes do vencimento'],
 'Liquidado no Prazo': ['Liquidados no Prazo',
  'Liquidados na data',
  'D0',
  'Liquidado no prazo'],
 'Liquidado Vencido': ['Liquidados (R$) em atraso', 'Liquidado vencido'],
 'Entre D1-D5': ['Entre D1-D5'],
 'Entre D1-D15': ['Entre D1-D15', 'Vencidos até 15 dias'],
 'Entre D6-D15': ['Entre D6-D15'],
 'Entre D16-D30': ['Vencidos até 30 dias'],
 'Acima de D30': ['Acima D30'],
 'Entre D31-D90': ['Vencidos até 90 dias'],
 'Entre D91-D120': ['Vencidos até 120 dias'],
 'Acima de D120': ['Vencidos acima de 120 dias'],
 'Recompra (R$)': ['*Recompra*',
  'Recompra',
  'Recompra do Valor Operado no Mês',
  'Recompra dentro de borderô (R$)'],
 'Concentração Top 10 Cedentes (R$)': ['10 Maiores Cedentes (R$)',
  'Concentrações 10 Maiores Cedentes (R$)\n (Vlr Presente-PDD)',
  'Concentrações Top10 Cedentes (R$)',
  'Concentrações Cedentes (R$)'],
 'Concentração Top 10 Sacados (R$)': ['10 Maiores Sacados (R$)',
  'Concentrações 10 Maiores Sacados (R$) \n(Vlr Presente-PDD)',
  'Concentrações Top10 Sacados (R$)',
  'Concentrações Sacados (R$)'],
 'Número de Funcionários': ['Numero de funcionarios',
  'Numero de funcionarios  CLT (*)'],
 'Volume Operado': ['Volume Operado no Mês (Vlr Nominal)',
  'Volume operado',
  'Valor Operado no Mês',
  'Valor Total Operado',
  'Volume Operado (desembolso)',
  'Valor Total Operado Nominal']}

In [202]:
def renomear_colunas_equivalentes(df, colunas_equivalentes_dict):
    renomear_dict = {}
    for nome_padrao, alternativas in colunas_equivalentes_dict.items():
        if alternativas is None: continue
        for nome in alternativas:
            if nome in df.columns:
                renomear_dict[nome] = nome_padrao
    return df.rename(columns=renomear_dict)

In [203]:
def verificar_padrao2(entry):
    text = str(entry).lower().strip()
    padroes = [
        r'(\d+)\s*-\s*(\d+)\s*dias?',                   # intervalo: 10 - 20 dias
        r'>\s*(\d+)\s*dias?',                           # > 120 dias
        r'<=\s*(\d+)\s*dias?'                           # <= 10 dias
    ]
    return any(re.search(p, text) for p in padroes)

def padronizar_colunas_dias2(df):
    columns = pd.Series(df.columns)
    result = columns.apply(verificar_padrao2)  # vetor booleano, ex: [True, False, False, ...]
    last_true_idx = None
    new_columns = []

    for idx, col_name in enumerate(columns):
        if not result.iloc[idx]:
            new_columns.append(col_name)
            last_true_idx = idx
        else:
            if last_true_idx is not None:
                new_name = f"({columns.iloc[last_true_idx]}){col_name}"
                new_columns.append(new_name)
            else:
                new_columns.append(col_name)
    df.columns = new_columns
    return df

In [204]:
import os

# Caminho da pasta com os arquivos CSV
caminho_pasta = '../out'

# Dicionário para armazenar os DataFrames
csv_dict = {}

def remover_sufixos(colunas):
    colunas_novas = []
    for col in colunas:
        # Remove sufixo do tipo .1, .2, .3 no final da string
        col_nova = re.sub(r'\.\d+$', '', col)
        colunas_novas.append(col_nova)
    return colunas_novas

# Percorre todos os arquivos na pasta
for arquivo in os.listdir(caminho_pasta):
    if arquivo.endswith('.csv'):
        caminho_arquivo = os.path.join(caminho_pasta, arquivo)
        nome_arquivo = os.path.splitext(arquivo)[0]  # Remove a extensão
        df = pd.read_csv(caminho_arquivo, sep=';', encoding='utf-8-sig', index_col = "Data", ).astype("float64")
        # ajuste encoding se necessário
        print(nome_arquivo)
        df.columns = remover_sufixos(df.columns)
        df = padronizar_colunas_dias(df)
        df = renomear_colunas_equivalentes(df, colunas_equivalentes)
        df = padronizar_colunas_dias2(df)
        csv_dict[nome_arquivo] = df

ALFA
0     False
1     False
2     False
3     False
4     False
      ...
67    False
68    False
69    False
70    False
71    False
Length: 72, dtype: bool
APPALOOSA
0     False
1     False
2     False
3     False
4     False
      ...
65    False
66    False
67    False
68    False
69    False
Length: 70, dtype: bool
ARTICO
0     False
1     False
2     False
3     False
4     False
      ...
73    False
74    False
75    False
76    False
77    False
Length: 78, dtype: bool
BARCELONA
0     False
1     False
2     False
3     False
4     False
      ...
61    False
62    False
63    False
64    False
65    False
Length: 66, dtype: bool
MULTIASSET
0     False
1     False
2     False
3     False
4     False
      ...
88    False
89    False
90    False
91    False
92    False
Length: 93, dtype: bool
MULTIPLIKE
0     False
1     False
2     False
3     False
4     False
      ...
65    False
66    False
67    False
68    False
69    False
Length: 70, dtype: bool
ONE7
0     False
1     False
2     False
3     False
4     False
      ...
56    False
57    False
58    False
59    False
60    False
Length: 61, dtype: bool
PAGOL
0     False
1     False
2     False
3     False
4     False
      ...
81    False
82    False
83    False
84    False
85    False
Length: 86, dtype: bool
PHD
0     False
1     False
2     False
3     False
4     False
      ...
67    False
68    False
69    False
70    False
71    False
Length: 72, dtype: bool
SOLAR
0     False
1     False
2     False
3     False
4     False
      ...
79    False
80    False
81    False
82    False
83    False
Length: 84, dtype: bool

In [205]:
from collections import Counter

contador_colunas = Counter()

for df in csv_dict.values():
    contador_colunas.update(df.columns.tolist())

colunas_ordenadas = dict(
    sorted(
        contador_colunas.items(),
        key=lambda x: (x[0] is None, str(x[0]))
    )
)

print(len(colunas_ordenadas))
for coluna, qtd in colunas_ordenadas.items():
    print(f"{coluna}: {qtd}")

237
$ Médio por cedente (*): 1
$ Médio por operação : 1
% Recompra: 1
% Subordinação: 1
% Total Direitos Creditórios sobre PL: 1
% do PL A Vencer: 1
% do PL FIDC Investido: 1
% do PL PDD: 1
% do PL Subordinada Júnior: 1
% do PL Subordinada Mezanino: 1
% do PL Subordinada Mezanino + Júnior: 1
% do PL Sênior: 1
% do PL Vencidos: 1
% do PL da Subordinada Júnior / PL Subordinada Meza + Jr.: 1
% do Volume liquidado antecipadamente: 1
% do Volume liquidado no prazo: 1
% do Volume liquidado recompra: 1
% do Volume liquidado vencido: 1
(% Total Direitos Creditórios sobre PL)0-5 dias: 2
(% Total Direitos Creditórios sobre PL)30-60 dias: 2
(% Total Direitos Creditórios sobre PL)5-30 dias: 2
(% Total Direitos Creditórios sobre PL)60-90 dias: 2
(% Total Direitos Creditórios sobre PL)90-120 dias: 2
(% Total Direitos Creditórios sobre PL)> 120 dias: 2
(Efeito Vagão)0-5 dias: 1
(Efeito Vagão)30-60 dias: 1
(Efeito Vagão)5-30 dias: 1
(Efeito Vagão)60-90 dias: 1
(Efeito Vagão)90-120 dias: 1
(Efeito Vagão)> 120 dias: 1
(PDD Total)0-15 dias: 4
(PDD Total)0-30 dias: 1
(PDD Total)0-5 dias: 1
(PDD Total)120-150 dias: 5
(PDD Total)15-30 dias: 5
(PDD Total)150-180 dias: 5
(PDD Total)180-360 dias: 1
(PDD Total)180-365 dias: 1
(PDD Total)180-999 dias: 3
(PDD Total)30-60 dias: 7
(PDD Total)5-30 dias: 1
(PDD Total)60-90 dias: 7
(PDD Total)90-120 dias: 7
(PDD Total)<= 15 dias: 1
(PDD Total)> 120 dias: 2
(Recompra/PL (%))0-30 dias: 2
(Recompra/PL (%))120-150 dias: 2
(Recompra/PL (%))150-180 dias: 2
(Recompra/PL (%))180-365 dias: 2
(Recompra/PL (%))30-60 dias: 2
(Recompra/PL (%))365-720 dias: 2
(Recompra/PL (%))60-90 dias: 2
(Recompra/PL (%))720-1080 dias: 2
(Recompra/PL (%))90-120 dias: 2
(Recompra/PL (%))> 1080 dias: 2
(Vencidos - PDD)0-30 dias: 1
(Vencidos - PDD)30-60 dias: 1
(Vencidos - PDD)60-90 dias: 1
(Vencidos - PDD)90-120 dias: 1
(Vencidos - PDD)> 120 dias: 1
(Vencidos Total)0-15 dias: 4
(Vencidos Total)0-30 dias: 1
(Vencidos Total)0-5 dias: 1
(Vencidos Total)120-150 dias: 4
(Vencidos Total)15-30 dias: 5
(Vencidos Total)150-180 dias: 4
(Vencidos Total)180-365 dias: 1
(Vencidos Total)180-999 dias: 3
(Vencidos Total)30-60 dias: 7
(Vencidos Total)5-30 dias: 1
(Vencidos Total)60-90 dias: 7
(Vencidos Total)90-120 dias: 7
(Vencidos Total)<= 15 dias: 1
(Vencidos Total)> 120 dias: 2
10 Maiores: 4
3 Maiores: 4
5 Maiores: 4
A vencer: 1
Acima de D120: 1
Acima de D30: 2
Amortização/Resgate Subordinada: 1
Aportes Subordinada Junior: 1
Assunção de Dívida : 1
CCB: 5
CCB/NCC - Máx 45% PL: 1
CDI: 2
CPR: 1
Caixa/Disponibilidades: 9
Captação/Resgate Superiores: 1
Carteira (Direitos Creditórios): 10
Carteira (Outros - Anima): 1
Carteira Direitos Creditórios Exceto PDD
 (Vlr Presente - Vlr PDD): 1
Carteira Total (Recebíveis): 1
Cartão de Crédito(Vlr Presente-PDD): 1
Cartão de crédito - Máx 10% PL: 1
Cedente 1: 10
Cedente 10: 10
Cedente 2: 10
Cedente 3: 10
Cedente 4: 10
Cedente 5: 10
Cedente 6: 10
Cedente 7: 10
Cedente 8: 10
Cedente 9: 10
Cedentes com Recuperação Judicial (Vlr Presente-PDD): 1
Cedentes com crédito tomado (*): 1
Cheques: 9
Comissaria: 1
Concentração Top 10 Cedentes (R$): 10
Concentração Top 10 Sacados (R$): 10
Confissão de Dívida: 4
Contrato: 8
Crédito médio por cedente: 1
Crédito médio por sacado: 1
DC/PL(%): 2
Debêntures: 1
Despesas: 1
Duplicata: 9
Duplicata de Serviço Físico: 3
Efeito Vagão: 1
Entre D1-D15: 1
Entre D1-D5: 2
Entre D16-D30: 3
Entre D31-D90: 1
Entre D6-D15: 2
Entre D91-D120: 1
Estimativa folha: 1
Estimativa folha CLT + PJ: 1
Excesso Índice Subordinada (% sobre PL): 1
Excesso Índice Subordinada Mezanino (% sobre PL): 1
Exposição Média por Cedente (R$): 1
FIDC investido: 1
Fatura de Cartão de Crédito: 1
Fundo Soberano: 2
Garantia CCB/NCC - Mín 30% sobre a carteira de CCB/NCC: 1
Intercompany: 1
Linhas Especiais (%): 1
Liquidado Antecipadamente: 4
Liquidado Total(R$): 8
Liquidado Vencido: 2
Liquidado no Prazo: 4
Liquidados: 1
Liquidados (%) em atraso: 1
Liquidados (%) em dia: 1
Liquidados (R$) em dia: 1
Maior Cedente - S/PL: 2
Maior Sacado - S/PL: 2
Maior cedente (máx 3,5%): 1
Nivel de confirmação (*): 1
Nivel de confirmação media: 2
Nota Comercial: 4
Nota Promissória: 4
Nº Operações: 1
Não Liquidado: 1
Número de Funcionários: 3
Número de Títulos (Fechamento): 2
Outros: 1
Outros Ativos: 1
Outros Créditos (Vlr Presente-PDD): 1
PDD (% DC): 2
PDD (% PL): 2
PDD Total: 10
PDD À Vencer: 6
PL Mezanino: 10
PL Mezanino %: 1
PL Subordinada Jr: 10
PL Subordinada Jr. %: 1
PL Sênior: 10
PL Sênior %: 1
PL Total: 10
Percentual Direitos Creditórios/PL: 1
Percentual de PDD (Direitos Creditórios): 1
Percentual de vencidos total (PL): 1
Percentual do PDD total (PL): 1
Prazo Médio: 10
Prazo Médio Operações no Mês: 1
Prazo Médio da Carteira a Vencer: 1
Precatório: 1
Quantidade de Cedentes: 9
Quantidade de Sacados: 9
Quantidade de títulos em aberto (Anima): 1
Recompra (R$): 10
Recompra/PL (%): 2
Remuneração Consultoria: 1
Remuneração consultoria: 2
Remuneração consultoria/gestão: 1
Rentabilidade Subordinada Junior (%CDI): 2
Resgates Subordinada Jr.: 3
Resgates Subordinada Mezanino: 3
Resgates Sênior: 2
Retorno Cota Subordinada: 8
Retorno Cota Subordinada - 12 Meses: 1
Retorno Cota Subordinada - Redução Sub Jr: 1
Retorno Cota Subordinada Jr: 1
Sacado 1: 10
Sacado 10: 10
Sacado 2: 10
Sacado 3: 10
Sacado 4: 10
Sacado 5: 10
Sacado 6: 10
Sacado 7: 10
Sacado 8: 10
Sacado 9: 10
Sacados com crédito tomado (*): 1
Saldo Médio Devedor por Cedente: 2
Saldo Médio Devedor por Sacado: 2
Somatória 10 maiores Cedente (máx 20%): 1
Somatória 20 maiores Sacados (máx 30%): 1
Somatória 50 maiores Sacados (máx 50%): 1
Subordinação Junior: 2
Subordinação Mezanino: 2
Subordinação Total (Junior + Mezanino): 2
Taxa Média: 10
Taxa Ponderada de Cessão/CDI (%): 2
Ticket Médio: 6
Ticket Médio (Valor Nominal): 1
Ticket Médio Cedentes: 1
Ticket Médio Sacados: 1
Total de Vencidos e nâo Pagos: 2
Títulos Liquidados (Qtde): 1
Títulos Liquidados em Dia (Qtde): 1
Títulos em RJ - Máx 10% PL: 1
Unidades de Recebível: 1
Valor Pago nas Operações no Mês: 1
Valor Total Operado Aquisição: 1
Valor médio por cedente: 1
Valores em Conciliação: 1
Vencidos (% PL): 1
Vencidos - PDD: 1
Vencidos - PDD (% PL): 2
Vencidos Total: 10
Volume Operado: 8
WO: 1
Índice Subordinada Mezanino: Jr./(Meza+Jr.): 1
Índice Subordinada: (Meza+Jr.)/PL Classe: 1

In [206]:
colunas_ordenadas = dict(
    sorted(
        contador_colunas.items(),
        key=lambda x: x[1],  # ordenar pelo valor (quantidade)
        reverse=True         # maior para menor
    )
)

colunas_ordenadas

{'PL Total': 10,
 'PL Sênior': 10,
 'PL Mezanino': 10,
 'PL Subordinada Jr': 10,
 'Carteira (Direitos Creditórios)': 10,
 'Taxa Média': 10,
 'Prazo Médio': 10,
 'Vencidos Total': 10,
 'PDD Total': 10,
 'Recompra (R$)': 10,
 'Cedente 1': 10,
 'Cedente 2': 10,
 'Cedente 3': 10,
 'Cedente 4': 10,
 'Cedente 5': 10,
 'Cedente 6': 10,
 'Cedente 7': 10,
 'Cedente 8': 10,
 'Cedente 9': 10,
 'Cedente 10': 10,
 'Sacado 1': 10,
 'Sacado 2': 10,
 'Sacado 3': 10,
 'Sacado 4': 10,
 'Sacado 5': 10,
 'Sacado 6': 10,
 'Sacado 7': 10,
 'Sacado 8': 10,
 'Sacado 9': 10,
 'Sacado 10': 10,
 'Concentração Top 10 Sacados (R$)': 10,
 'Concentração Top 10 Cedentes (R$)': 10,
 'Duplicata': 9,
 'Cheques': 9,
 'Caixa/Disponibilidades': 9,
 'Quantidade de Cedentes': 9,
 'Quantidade de Sacados': 9,
 'Volume Operado': 8,
 'Liquidado Total(R$)': 8,
 'Retorno Cota Subordinada': 8,
 'Contrato': 8,
 '(Vencidos Total)30-60 dias': 7,
 '(Vencidos Total)60-90 dias': 7,
 '(Vencidos Total)90-120 dias': 7,
 '(PDD Total)30-60 dias': 7,
 '(PDD Total)60-90 dias': 7,
 '(PDD Total)90-120 dias': 7,
 'PDD À Vencer': 6,
 'Ticket Médio': 6,
 '(Vencidos Total)15-30 dias': 5,
 '(PDD Total)15-30 dias': 5,
 '(PDD Total)120-150 dias': 5,
 '(PDD Total)150-180 dias': 5,
 'CCB': 5,
 '(Vencidos Total)0-15 dias': 4,
 '(Vencidos Total)120-150 dias': 4,
 '(Vencidos Total)150-180 dias': 4,
 '(PDD Total)0-15 dias': 4,
 'Nota Promissória': 4,
 'Nota Comercial': 4,
 'Confissão de Dívida': 4,
 'Liquidado Antecipadamente': 4,
 'Liquidado no Prazo': 4,
 '3 Maiores': 4,
 '5 Maiores': 4,
 '10 Maiores': 4,
 '(Vencidos Total)180-999 dias': 3,
 '(PDD Total)180-999 dias': 3,
 'Número de Funcionários': 3,
 'Entre D16-D30': 3,
 'Duplicata de Serviço Físico': 3,
 'Resgates Subordinada Mezanino': 3,
 'Resgates Subordinada Jr.': 3,
 'Fundo Soberano': 2,
 'Nivel de confirmação media': 2,
 'Remuneração consultoria': 2,
 '(Vencidos Total)> 120 dias': 2,
 '(PDD Total)> 120 dias': 2,
 'Rentabilidade Subordinada Junior (%CDI)': 2,
 'Subordinação Junior': 2,
 'Subordinação Mezanino': 2,
 'Subordinação Total (Junior + Mezanino)': 2,
 'Resgates Sênior': 2,
 'DC/PL(%)': 2,
 'Vencidos - PDD (% PL)': 2,
 'PDD (% PL)': 2,
 'PDD (% DC)': 2,
 'Taxa Ponderada de Cessão/CDI (%)': 2,
 'CDI': 2,
 'Número de Títulos (Fechamento)': 2,
 'Liquidado Vencido': 2,
 'Entre D1-D5': 2,
 'Entre D6-D15': 2,
 'Acima de D30': 2,
 'Recompra/PL (%)': 2,
 '(Recompra/PL (%))0-30 dias': 2,
 '(Recompra/PL (%))30-60 dias': 2,
 '(Recompra/PL (%))60-90 dias': 2,
 '(Recompra/PL (%))90-120 dias': 2,
 '(Recompra/PL (%))120-150 dias': 2,
 '(Recompra/PL (%))150-180 dias': 2,
 '(Recompra/PL (%))180-365 dias': 2,
 '(Recompra/PL (%))365-720 dias': 2,
 '(Recompra/PL (%))720-1080 dias': 2,
 '(Recompra/PL (%))> 1080 dias': 2,
 'Total de Vencidos e nâo Pagos': 2,
 'Saldo Médio Devedor por Cedente': 2,
 'Maior Cedente - S/PL': 2,
 'Saldo Médio Devedor por Sacado': 2,
 'Maior Sacado - S/PL': 2,
 '(% Total Direitos Creditórios sobre PL)0-5 dias': 2,
 '(% Total Direitos Creditórios sobre PL)5-30 dias': 2,
 '(% Total Direitos Creditórios sobre PL)30-60 dias': 2,
 '(% Total Direitos Creditórios sobre PL)60-90 dias': 2,
 '(% Total Direitos Creditórios sobre PL)90-120 dias': 2,
 '(% Total Direitos Creditórios sobre PL)> 120 dias': 2,
 'Carteira Total (Recebíveis)': 1,
 'Carteira (Outros - Anima)': 1,
 'Percentual Direitos Creditórios/PL': 1,
 'Valor médio por cedente': 1,
 'Quantidade de títulos em aberto (Anima)': 1,
 '$ Médio por operação ': 1,
 'Percentual de vencidos total (PL)': 1,
 'Percentual do PDD total (PL)': 1,
 'Percentual de PDD (Direitos Creditórios)': 1,
 'Retorno Cota Subordinada - Redução Sub Jr': 1,
 'Estimativa folha': 1,
 'Retorno Cota Subordinada Jr': 1,
 'Amortização/Resgate Subordinada': 1,
 'Aportes Subordinada Junior': 1,
 'Remuneração Consultoria': 1,
 'Carteira Direitos Creditórios Exceto PDD\n (Vlr Presente - Vlr PDD)': 1,
 'Prazo Médio Operações no Mês': 1,
 'Cartão de Crédito(Vlr Presente-PDD)': 1,
 'Outros Créditos (Vlr Presente-PDD)': 1,
 'Cedentes com Recuperação Judicial (Vlr Presente-PDD)': 1,
 'CPR': 1,
 'Debêntures': 1,
 'Fatura de Cartão de Crédito': 1,
 'Precatório': 1,
 'Unidades de Recebível': 1,
 'Outros': 1,
 '(Vencidos Total)0-30 dias': 1,
 '(PDD Total)0-30 dias': 1,
 'Vencidos - PDD': 1,
 '(Vencidos - PDD)0-30 dias': 1,
 '(Vencidos - PDD)30-60 dias': 1,
 '(Vencidos - PDD)60-90 dias': 1,
 '(Vencidos - PDD)90-120 dias': 1,
 '(Vencidos - PDD)> 120 dias': 1,
 'Liquidados': 1,
 'Entre D1-D15': 1,
 'Entre D31-D90': 1,
 'Entre D91-D120': 1,
 'Acima de D120': 1,
 'Retorno Cota Subordinada - 12 Meses': 1,
 'Intercompany': 1,
 'Comissaria': 1,
 'Linhas Especiais (%)': 1,
 'Valores em Conciliação': 1,
 'Títulos Liquidados (Qtde)': 1,
 'Títulos Liquidados em Dia (Qtde)': 1,
 'Liquidados (R$) em dia': 1,
 'Liquidados (%) em dia': 1,
 'Liquidados (%) em atraso': 1,
 'Não Liquidado': 1,
 'PL Sênior %': 1,
 'PL Mezanino %': 1,
 'PL Subordinada Jr. %': 1,
 'Títulos em RJ - Máx 10% PL': 1,
 'CCB/NCC - Máx 45% PL': 1,
 'Garantia CCB/NCC - Mín 30% sobre a carteira de CCB/NCC': 1,
 'Cartão de crédito - Máx 10% PL': 1,
 'Cedentes com crédito tomado (*)': 1,
 'Sacados com crédito tomado (*)': 1,
 '$ Médio por cedente (*)': 1,
 'Nivel de confirmação (*)': 1,
 '(Vencidos Total)0-5 dias': 1,
 '(Vencidos Total)5-30 dias': 1,
 '(PDD Total)0-5 dias': 1,
 '(PDD Total)5-30 dias': 1,
 'Maior cedente (máx 3,5%)': 1,
 'Somatória 10 maiores Cedente (máx 20%)': 1,
 'Somatória 20 maiores Sacados (máx 30%)': 1,
 'Somatória 50 maiores Sacados (máx 50%)': 1,
 'Estimativa folha CLT + PJ': 1,
 'Remuneração consultoria/gestão': 1,
 '% Subordinação': 1,
 'Ticket Médio (Valor Nominal)': 1,
 'Assunção de Dívida ': 1,
 '(PDD Total)180-360 dias': 1,
 '% Recompra': 1,
 'Captação/Resgate Superiores': 1,
 'Vencidos (% PL)': 1,
 'Valor Total Operado Aquisição': 1,
 'Valor Pago nas Operações no Mês': 1,
 'Prazo Médio da Carteira a Vencer': 1,
 'Exposição Média por Cedente (R$)': 1,
 '(Vencidos Total)<= 15 dias': 1,
 '(Vencidos Total)180-365 dias': 1,
 '(PDD Total)<= 15 dias': 1,
 '(PDD Total)180-365 dias': 1,
 'WO': 1,
 'Ticket Médio Cedentes': 1,
 'Ticket Médio Sacados': 1,
 '% do PL Sênior': 1,
 '% do PL Subordinada Mezanino': 1,
 '% do PL Subordinada Mezanino + Júnior': 1,
 '% do PL Subordinada Júnior': 1,
 '% do PL da Subordinada Júnior / PL Subordinada Meza + Jr.': 1,
 'Índice Subordinada: (Meza+Jr.)/PL Classe': 1,
 'Excesso Índice Subordinada (% sobre PL)': 1,
 'Índice Subordinada Mezanino: Jr./(Meza+Jr.)': 1,
 'Excesso Índice Subordinada Mezanino (% sobre PL)': 1,
 'A vencer': 1,
 '% do PL A Vencer': 1,
 '% do PL Vencidos': 1,
 '% do PL PDD': 1,
 'FIDC investido': 1,
 '% do PL FIDC Investido': 1,
 '% Total Direitos Creditórios sobre PL': 1,
 'Efeito Vagão': 1,
 '(Efeito Vagão)0-5 dias': 1,
 '(Efeito Vagão)5-30 dias': 1,
 '(Efeito Vagão)30-60 dias': 1,
 '(Efeito Vagão)60-90 dias': 1,
 '(Efeito Vagão)90-120 dias': 1,
 '(Efeito Vagão)> 120 dias': 1,
 'Outros Ativos': 1,
 'Despesas': 1,
 'Crédito médio por cedente': 1,
 'Crédito médio por sacado': 1,
 'Nº Operações': 1,
 '% do Volume liquidado no prazo': 1,
 '% do Volume liquidado antecipadamente': 1,
 '% do Volume liquidado vencido': 1,
 '% do Volume liquidado recompra': 1}

In [207]:
for key in csv_dict.keys():
    print(key)
    print(csv_dict[key].columns)

ALFA
Index(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr',
       'Carteira Total (Recebíveis)', 'Carteira (Direitos Creditórios)',
       'Duplicata', 'Cheques', 'Carteira (Outros - Anima)',
       'Percentual Direitos Creditórios/PL', 'Caixa/Disponibilidades',
       'Fundo Soberano', 'Quantidade de Cedentes', 'Valor médio por cedente',
       'Quantidade de Sacados', 'Quantidade de títulos em aberto (Anima)',
       '$ Médio por operação ', 'Taxa Média', 'Nivel de confirmação media',
       'Prazo Médio', 'Volume Operado', 'Liquidado Total(R$)',
       'Vencidos Total', '(Vencidos Total)0-15 dias',
       '(Vencidos Total)15-30 dias', '(Vencidos Total)30-60 dias',
       '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias',
       '(Vencidos Total)120-150 dias', '(Vencidos Total)150-180 dias',
       '(Vencidos Total)180-999 dias', 'Percentual de vencidos total (PL)',
       'PDD Total', '(PDD Total)0-15 dias', '(PDD Total)15-30 dias',
       '(PDD Total)30-60 dias', '(PDD Total)60-90 dias',
       '(PDD Total)90-120 dias', '(PDD Total)120-150 dias',
       '(PDD Total)150-180 dias', '(PDD Total)180-999 dias', 'PDD À Vencer',
       'Percentual do PDD total (PL)',
       'Percentual de PDD (Direitos Creditórios)', 'Recompra (R$)',
       'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5',
       'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10',
       'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6',
       'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10',
       'Retorno Cota Subordinada', 'Retorno Cota Subordinada - Redução Sub Jr',
       'Número de Funcionários', 'Estimativa folha', 'Remuneração consultoria',
       'Concentração Top 10 Sacados (R$)',
       'Concentração Top 10 Cedentes (R$)'],
      dtype='object')
APPALOOSA
Index(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr',
       'Retorno Cota Subordinada Jr', 'Amortização/Resgate Subordinada',
       'Aportes Subordinada Junior', 'Remuneração Consultoria',
       'Volume Operado', 'Carteira (Direitos Creditórios)',
       'Carteira Direitos Creditórios Exceto PDD\n (Vlr Presente - Vlr PDD)',
       'Caixa/Disponibilidades', 'Quantidade de Cedentes',
       'Quantidade de Sacados', 'Ticket Médio', 'Taxa Média', 'Prazo Médio',
       'Prazo Médio Operações no Mês', 'Duplicata', 'Cheques', 'Contrato',
       'Cartão de Crédito(Vlr Presente-PDD)', 'Nota Promissória', 'CCB',
       'Nota Comercial', 'Outros Créditos (Vlr Presente-PDD)',
       'Cedentes com Recuperação Judicial (Vlr Presente-PDD)',
       'Vencidos Total', '(Vencidos Total)0-15 dias',
       '(Vencidos Total)15-30 dias', '(Vencidos Total)30-60 dias',
       '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias',
       '(Vencidos Total)120-150 dias', '(Vencidos Total)150-180 dias',
       '(Vencidos Total)180-999 dias', 'PDD Total', '(PDD Total)0-15 dias',
       '(PDD Total)15-30 dias', '(PDD Total)30-60 dias',
       '(PDD Total)60-90 dias', '(PDD Total)90-120 dias',
       '(PDD Total)120-150 dias', '(PDD Total)150-180 dias',
       '(PDD Total)180-999 dias', 'PDD À Vencer', 'Liquidado Total(R$)',
       'Recompra (R$)', 'Concentração Top 10 Cedentes (R$)', 'Cedente 1',
       'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6',
       'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10',
       'Concentração Top 10 Sacados (R$)', 'Sacado 1', 'Sacado 2', 'Sacado 3',
       'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9',
       'Sacado 10'],
      dtype='object')
ARTICO
Index(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr',
       'Carteira (Direitos Creditórios)', 'Caixa/Disponibilidades',
       'Quantidade de Cedentes', 'Quantidade de Sacados', 'Ticket Médio',
       'Taxa Média', 'Prazo Médio', 'CCB', 'Cheques', 'Confissão de Dívida',
       'Contrato', 'CPR', 'Debêntures', 'Duplicata',
       'Fatura de Cartão de Crédito', 'Nota Comercial', 'Nota Promissória',
       'Precatório', 'Unidades de Recebível', 'Outros', 'Vencidos Total',
       '(Vencidos Total)0-30 dias', '(Vencidos Total)30-60 dias',
       '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias',
       '(Vencidos Total)> 120 dias', 'PDD Total', '(PDD Total)0-30 dias',
       '(PDD Total)30-60 dias', '(PDD Total)60-90 dias',
       '(PDD Total)90-120 dias', '(PDD Total)> 120 dias', 'PDD À Vencer',
       'Vencidos - PDD', '(Vencidos - PDD)0-30 dias',
       '(Vencidos - PDD)30-60 dias', '(Vencidos - PDD)60-90 dias',
       '(Vencidos - PDD)90-120 dias', '(Vencidos - PDD)> 120 dias',
       'Concentração Top 10 Cedentes (R$)', 'Cedente 1', 'Cedente 2',
       'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7',
       'Cedente 8', 'Cedente 9', 'Cedente 10',
       'Concentração Top 10 Sacados (R$)', 'Sacado 1', 'Sacado 2', 'Sacado 3',
       'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9',
       'Sacado 10', 'Volume Operado', 'Recompra (R$)', 'Liquidados',
       'Liquidado Total(R$)', 'Liquidado Antecipadamente',
       'Liquidado no Prazo', 'Entre D1-D15', 'Entre D16-D30', 'Entre D31-D90',
       'Entre D91-D120', 'Acima de D120', 'Retorno Cota Subordinada',
       'Retorno Cota Subordinada - 12 Meses'],
      dtype='object')
BARCELONA
Index(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr',
       'Carteira (Direitos Creditórios)', 'Caixa/Disponibilidades',
       'Quantidade de Cedentes', 'Quantidade de Sacados', 'Ticket Médio',
       'Taxa Média', 'Prazo Médio', 'Cheques', 'Confissão de Dívida',
       'Contrato', 'Duplicata', 'Duplicata de Serviço Físico', 'CCB',
       'Nota Promissória', 'Nota Comercial', 'Intercompany', 'Comissaria',
       'Linhas Especiais (%)', 'Vencidos Total', '(Vencidos Total)0-15 dias',
       '(Vencidos Total)15-30 dias', '(Vencidos Total)30-60 dias',
       '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias',
       '(Vencidos Total)120-150 dias', '(Vencidos Total)150-180 dias',
       '(Vencidos Total)180-999 dias', 'PDD Total', '(PDD Total)0-15 dias',
       '(PDD Total)15-30 dias', '(PDD Total)30-60 dias',
       '(PDD Total)60-90 dias', '(PDD Total)90-120 dias',
       '(PDD Total)120-150 dias', '(PDD Total)150-180 dias',
       '(PDD Total)180-999 dias', 'PDD À Vencer', 'Liquidado Total(R$)',
       'Recompra (R$)', 'Concentração Top 10 Cedentes (R$)', 'Cedente 1',
       'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6',
       'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10',
       'Concentração Top 10 Sacados (R$)', 'Sacado 1', 'Sacado 2', 'Sacado 3',
       'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9',
       'Sacado 10', 'Retorno Cota Subordinada'],
      dtype='object')
MULTIASSET
Index(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr',
       'Retorno Cota Subordinada', 'Rentabilidade Subordinada Junior (%CDI)',
       'Subordinação Junior', 'Subordinação Mezanino',
       'Subordinação Total (Junior + Mezanino)', 'Resgates Sênior',
       'Resgates Subordinada Mezanino', 'Resgates Subordinada Jr.',
       'Carteira (Direitos Creditórios)', 'DC/PL(%)', 'Caixa/Disponibilidades',
       'Vencidos Total', 'Valores em Conciliação', 'Vencidos - PDD (% PL)',
       'PDD Total', 'PDD (% PL)', 'PDD (% DC)', 'Ticket Médio', 'Prazo Médio',
       'Taxa Média', 'Taxa Ponderada de Cessão/CDI (%)', 'CDI',
       'Volume Operado', 'Número de Títulos (Fechamento)', 'Duplicata',
       'Contrato', 'Cheques', 'Nota Promissória', 'Títulos Liquidados (Qtde)',
       'Liquidado Total(R$)', 'Títulos Liquidados em Dia (Qtde)',
       'Liquidados (R$) em dia', 'Liquidados (%) em dia', 'Liquidado Vencido',
       'Liquidados (%) em atraso', 'Liquidado Antecipadamente',
       'Liquidado no Prazo', 'Entre D1-D5', 'Entre D6-D15', 'Entre D16-D30',
       'Acima de D30', 'Não Liquidado', 'Recompra (R$)', 'Recompra/PL (%)',
       '(Recompra/PL (%))0-30 dias', '(Recompra/PL (%))30-60 dias',
       '(Recompra/PL (%))60-90 dias', '(Recompra/PL (%))90-120 dias',
       '(Recompra/PL (%))120-150 dias', '(Recompra/PL (%))150-180 dias',
       '(Recompra/PL (%))180-365 dias', '(Recompra/PL (%))365-720 dias',
       '(Recompra/PL (%))720-1080 dias', '(Recompra/PL (%))> 1080 dias',
       'Total de Vencidos e nâo Pagos', 'Quantidade de Cedentes',
       'Saldo Médio Devedor por Cedente', 'Concentração Top 10 Cedentes (R$)',
       'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5',
       'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10',
       'Maior Cedente - S/PL', '3 Maiores', '5 Maiores', '10 Maiores',
       'Quantidade de Sacados', 'Saldo Médio Devedor por Sacado',
       'Concentração Top 10 Sacados (R$)', 'Sacado 1', 'Sacado 2', 'Sacado 3',
       'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9',
       'Sacado 10', 'Maior Sacado - S/PL', '3 Maiores', '5 Maiores',
       '10 Maiores'],
      dtype='object')
MULTIPLIKE
Index(['PL Total', 'PL Sênior', 'PL Sênior %', 'PL Mezanino', 'PL Mezanino %',
       'PL Subordinada Jr', 'PL Subordinada Jr. %',
       'Carteira (Direitos Creditórios)', 'Duplicata',
       'Títulos em RJ - Máx 10% PL', 'CCB/NCC - Máx 45% PL',
       'Garantia CCB/NCC - Mín 30% sobre a carteira de CCB/NCC',
       'Cartão de crédito - Máx 10% PL', 'Contrato', 'Cheques',
       'Caixa/Disponibilidades', 'Fundo Soberano',
       'Cedentes com crédito tomado (*)', 'Sacados com crédito tomado (*)',
       '$ Médio por cedente (*)', 'Taxa Média', 'Nivel de confirmação (*)',
       'Prazo Médio', 'Volume Operado', 'Vencidos Total',
       '(Vencidos Total)0-5 dias', '(Vencidos Total)5-30 dias',
       '(Vencidos Total)30-60 dias', '(Vencidos Total)60-90 dias',
       '(Vencidos Total)90-120 dias', '(Vencidos Total)> 120 dias',
       'PDD Total', '(PDD Total)0-5 dias', '(PDD Total)5-30 dias',
       '(PDD Total)30-60 dias', '(PDD Total)60-90 dias',
       '(PDD Total)90-120 dias', '(PDD Total)> 120 dias', 'Recompra (R$)',
       'Liquidado Total(R$)', 'Cedente 1', 'Cedente 2', 'Cedente 3',
       'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8',
       'Cedente 9', 'Cedente 10', 'Maior cedente (máx 3,5%)',
       'Somatória 10 maiores Cedente (máx 20%)', 'Sacado 1', 'Sacado 2',
       'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8',
       'Sacado 9', 'Sacado 10', 'Somatória 20 maiores Sacados (máx 30%)',
       'Somatória 50 maiores Sacados (máx 50%)', 'Retorno Cota Subordinada',
       'Número de Funcionários', 'Estimativa folha CLT + PJ',
       'Remuneração consultoria/gestão', 'Concentração Top 10 Sacados (R$)',
       'Concentração Top 10 Cedentes (R$)'],
      dtype='object')
ONE7
Index(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr',
       '% Subordinação', 'Carteira (Direitos Creditórios)',
       'Quantidade de Cedentes', 'Quantidade de Sacados', 'Ticket Médio',
       'Ticket Médio (Valor Nominal)', 'Taxa Média',
       'Nivel de confirmação media', 'Prazo Médio', 'Cheques',
       'Confissão de Dívida', 'Contrato', 'Duplicata',
       'Duplicata de Serviço Físico', 'Assunção de Dívida ', 'Vencidos Total',
       '(Vencidos Total)0-15 dias', '(Vencidos Total)15-30 dias',
       '(Vencidos Total)30-60 dias', '(Vencidos Total)60-90 dias',
       '(Vencidos Total)90-120 dias', 'PDD Total', '(PDD Total)0-15 dias',
       '(PDD Total)15-30 dias', '(PDD Total)30-60 dias',
       '(PDD Total)60-90 dias', '(PDD Total)90-120 dias',
       '(PDD Total)120-150 dias', '(PDD Total)150-180 dias',
       '(PDD Total)180-360 dias', 'PDD À Vencer', 'Recompra (R$)',
       '% Recompra', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4',
       'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9',
       'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4',
       'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10',
       'Retorno Cota Subordinada', 'Número de Funcionários',
       'Concentração Top 10 Sacados (R$)',
       'Concentração Top 10 Cedentes (R$)'],
      dtype='object')
PAGOL
Index(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr',
       'Retorno Cota Subordinada', 'Rentabilidade Subordinada Junior (%CDI)',
       'Subordinação Junior', 'Subordinação Mezanino',
       'Subordinação Total (Junior + Mezanino)', 'Captação/Resgate Superiores',
       'Resgates Subordinada Mezanino', 'Resgates Subordinada Jr.',
       'Carteira (Direitos Creditórios)', 'DC/PL(%)', 'Caixa/Disponibilidades',
       'Vencidos Total', 'Vencidos (% PL)', 'Vencidos - PDD (% PL)',
       'PDD Total', 'PDD (% PL)', 'PDD (% DC)', 'Ticket Médio', 'Prazo Médio',
       'Taxa Média', 'Taxa Ponderada de Cessão/CDI (%)', 'CDI',
       'Volume Operado', 'Valor Total Operado Aquisição',
       'Número de Títulos (Fechamento)', 'Duplicata', 'Contrato', 'CCB',
       'Cheques', 'Liquidado Antecipadamente', 'Liquidado no Prazo',
       'Entre D1-D5', 'Entre D6-D15', 'Entre D16-D30', 'Acima de D30',
       'Recompra (R$)', 'Recompra/PL (%)', '(Recompra/PL (%))0-30 dias',
       '(Recompra/PL (%))30-60 dias', '(Recompra/PL (%))60-90 dias',
       '(Recompra/PL (%))90-120 dias', '(Recompra/PL (%))120-150 dias',
       '(Recompra/PL (%))150-180 dias', '(Recompra/PL (%))180-365 dias',
       '(Recompra/PL (%))365-720 dias', '(Recompra/PL (%))720-1080 dias',
       '(Recompra/PL (%))> 1080 dias', 'Total de Vencidos e nâo Pagos',
       'Quantidade de Cedentes', 'Saldo Médio Devedor por Cedente',
       'Concentração Top 10 Cedentes (R$)', 'Cedente 1', 'Cedente 2',
       'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7',
       'Cedente 8', 'Cedente 9', 'Cedente 10', 'Maior Cedente - S/PL',
       '3 Maiores', '5 Maiores', '10 Maiores', 'Quantidade de Sacados',
       'Saldo Médio Devedor por Sacado', 'Concentração Top 10 Sacados (R$)',
       'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6',
       'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10', 'Maior Sacado - S/PL',
       '3 Maiores', '5 Maiores', '10 Maiores'],
      dtype='object')
PHD
Index(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr',
       'Resgates Sênior', 'Resgates Subordinada Mezanino',
       'Resgates Subordinada Jr.', 'Caixa/Disponibilidades', 'Volume Operado',
       'Valor Pago nas Operações no Mês', 'Quantidade de Cedentes',
       'Quantidade de Sacados', 'Taxa Média', 'Prazo Médio',
       'Prazo Médio da Carteira a Vencer', 'Exposição Média por Cedente (R$)',
       'Retorno Cota Subordinada', 'Remuneração consultoria',
       'Liquidado Total(R$)', 'Recompra (R$)',
       'Carteira (Direitos Creditórios)', 'Duplicata', 'Cheques',
       'Duplicata de Serviço Físico', 'Contrato', 'Confissão de Dívida',
       'Nota Comercial', 'CCB', 'Vencidos Total', '(Vencidos Total)<= 15 dias',
       '(Vencidos Total)15-30 dias', '(Vencidos Total)30-60 dias',
       '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias',
       '(Vencidos Total)120-150 dias', '(Vencidos Total)150-180 dias',
       '(Vencidos Total)180-365 dias', 'PDD Total', '(PDD Total)<= 15 dias',
       '(PDD Total)15-30 dias', '(PDD Total)30-60 dias',
       '(PDD Total)60-90 dias', '(PDD Total)90-120 dias',
       '(PDD Total)120-150 dias', '(PDD Total)150-180 dias',
       '(PDD Total)180-365 dias', 'PDD À Vencer', 'WO',
       'Concentração Top 10 Cedentes (R$)', 'Cedente 1', 'Cedente 2',
       'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7',
       'Cedente 8', 'Cedente 9', 'Cedente 10',
       'Concentração Top 10 Sacados (R$)', 'Sacado 1', 'Sacado 2', 'Sacado 3',
       'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9',
       'Sacado 10', 'Ticket Médio Cedentes', 'Ticket Médio Sacados'],
      dtype='object')
SOLAR
Index(['PL Sênior', '% do PL Sênior', 'PL Mezanino',
       '% do PL Subordinada Mezanino', '% do PL Subordinada Mezanino + Júnior',
       'PL Subordinada Jr', '% do PL Subordinada Júnior',
       '% do PL da Subordinada Júnior / PL Subordinada Meza + Jr.', 'PL Total',
       'Índice Subordinada: (Meza+Jr.)/PL Classe',
       'Excesso Índice Subordinada (% sobre PL)',
       'Índice Subordinada Mezanino: Jr./(Meza+Jr.)',
       'Excesso Índice Subordinada Mezanino (% sobre PL)', 'A vencer',
       '% do PL A Vencer', 'Vencidos Total', '% do PL Vencidos', 'PDD Total',
       '% do PL PDD', 'FIDC investido', '% do PL FIDC Investido',
       'Carteira (Direitos Creditórios)',
       '% Total Direitos Creditórios sobre PL',
       '(% Total Direitos Creditórios sobre PL)0-5 dias',
       '(% Total Direitos Creditórios sobre PL)5-30 dias',
       '(% Total Direitos Creditórios sobre PL)30-60 dias',
       '(% Total Direitos Creditórios sobre PL)60-90 dias',
       '(% Total Direitos Creditórios sobre PL)90-120 dias',
       '(% Total Direitos Creditórios sobre PL)> 120 dias',
       '(% Total Direitos Creditórios sobre PL)0-5 dias',
       '(% Total Direitos Creditórios sobre PL)5-30 dias',
       '(% Total Direitos Creditórios sobre PL)30-60 dias',
       '(% Total Direitos Creditórios sobre PL)60-90 dias',
       '(% Total Direitos Creditórios sobre PL)90-120 dias',
       '(% Total Direitos Creditórios sobre PL)> 120 dias', 'Efeito Vagão',
       '(Efeito Vagão)0-5 dias', '(Efeito Vagão)5-30 dias',
       '(Efeito Vagão)30-60 dias', '(Efeito Vagão)60-90 dias',
       '(Efeito Vagão)90-120 dias', '(Efeito Vagão)> 120 dias', 'Cedente 1',
       'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6',
       'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10',
       'Quantidade de Cedentes', 'Sacado 1', 'Sacado 2', 'Sacado 3',
       'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9',
       'Sacado 10', 'Quantidade de Sacados', 'Caixa/Disponibilidades',
       'Outros Ativos', 'Despesas', 'Volume Operado',
       'Crédito médio por cedente', 'Crédito médio por sacado', 'Taxa Média',
       'Prazo Médio', 'Nº Operações', 'Liquidado Total(R$)',
       'Liquidado no Prazo', '% do Volume liquidado no prazo',
       'Liquidado Antecipadamente', '% do Volume liquidado antecipadamente',
       'Liquidado Vencido', '% do Volume liquidado vencido', 'Recompra (R$)',
       '% do Volume liquidado recompra', 'Concentração Top 10 Sacados (R$)',
       'Concentração Top 10 Cedentes (R$)'],
      dtype='object')

In [208]:
colunas_equivalentes.keys()

dict_keys(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Carteira (Direitos Creditórios)', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Caixa/Disponibilidades', 'Taxa Média', 'Prazo Médio', 'Ticket Médio', 'Retorno Cota Subordinada', 'Cheques', 'Duplicata', 'Duplicata de Serviço Físico', 'Contrato', 'Nota Comercial', 'Confissão de Dívida', 'Nota Promissória', 'CCB', 'Resgates Subordinada Jr.', 'Resgates Subordinada Mezanino', 'Resgates Sênior', 'Vencidos Total', 'PDD Total', 'PDD À Vencer', 'Liquidado Total(R$)', 'Liquidado Antecipadamente', 'Liquidado no Prazo', 'Liquidado Vencido', 'Entre D1-D5', 'Entre D1-D15', 'Entre D6-D15', 'Entre D16-D30', 'Acima de D30', 'Entre D31-D90', 'Entre D91-D120', 'Acima de D120', 'Recompra (R$)', 'Concentração Top 10 Cedentes (R$)', 'Concentração Top 10 Sacados (R$)', 'Número de Funcionários', 'Volume Operado'])

In [209]:
def selecionar_colunas_por_nome(dataframes, padroes_colunas):
    # Usa apenas as chaves como nomes exatos de colunas a buscar
    nomes_colunas_procuradas = list(padroes_colunas.keys())
    print("Liquidado Total(R$)" in padroes_colunas)
    print(nomes_colunas_procuradas)
    resultado = {}

    for nome_df, df in dataframes.items():
        colunas_encontradas = []
        for col in df.columns:
            if col in nomes_colunas_procuradas:
                colunas_encontradas.append(col)
        resultado[nome_df] = colunas_encontradas

    return resultado

def selecionar_colunas_por_regex(dataframes, padroes_colunas):
    teste = list(padroes_colunas.values())[0]

    padroes_compilados = [re.compile(p) for p in teste]

    resultado = {}

    for nome_df, df in dataframes.items():
        colunas_capturadas = []
        for col in df.columns:
            for padrao in padroes_compilados:
                if padrao.fullmatch(str(col)):
                    colunas_capturadas.append(col)
                    break
        resultado[nome_df] = colunas_capturadas

    return resultado

list1 = selecionar_colunas_por_nome(csv_dict, colunas_equivalentes)
list2 = selecionar_colunas_por_regex(csv_dict, padroes_regex_col)

True
['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Carteira (Direitos Creditórios)', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Caixa/Disponibilidades', 'Taxa Média', 'Prazo Médio', 'Ticket Médio', 'Retorno Cota Subordinada', 'Cheques', 'Duplicata', 'Duplicata de Serviço Físico', 'Contrato', 'Nota Comercial', 'Confissão de Dívida', 'Nota Promissória', 'CCB', 'Resgates Subordinada Jr.', 'Resgates Subordinada Mezanino', 'Resgates Sênior', 'Vencidos Total', 'PDD Total', 'PDD À Vencer', 'Liquidado Total(R$)', 'Liquidado Antecipadamente', 'Liquidado no Prazo', 'Liquidado Vencido', 'Entre D1-D5', 'Entre D1-D15', 'Entre D6-D15', 'Entre D16-D30', 'Acima de D30', 'Entre D31-D90', 'Entre D91-D120', 'Acima de D120', 'Recompra (R$)', 'Concentração Top 10 Cedentes (R$)', 'Concentração Top 10 Sacados (R$)', 'Número de Funcionários', 'Volume Operado']

In [210]:
#resultado = list1
resultado = {k: list1.get(k, []) + list2.get(k, []) for k in list1.keys()}

resultado

{'ALFA': ['PL Total',
  'PL Sênior',
  'PL Mezanino',
  'PL Subordinada Jr',
  'Carteira (Direitos Creditórios)',
  'Duplicata',
  'Cheques',
  'Caixa/Disponibilidades',
  'Quantidade de Cedentes',
  'Quantidade de Sacados',
  'Taxa Média',
  'Prazo Médio',
  'Volume Operado',
  'Liquidado Total(R$)',
  'Vencidos Total',
  'PDD Total',
  'PDD À Vencer',
  'Recompra (R$)',
  'Retorno Cota Subordinada',
  'Número de Funcionários',
  'Concentração Top 10 Sacados (R$)',
  'Concentração Top 10 Cedentes (R$)',
  '(Vencidos Total)0-15 dias',
  '(Vencidos Total)15-30 dias',
  '(Vencidos Total)30-60 dias',
  '(Vencidos Total)60-90 dias',
  '(Vencidos Total)90-120 dias',
  '(Vencidos Total)120-150 dias',
  '(Vencidos Total)150-180 dias',
  '(Vencidos Total)180-999 dias',
  '(PDD Total)0-15 dias',
  '(PDD Total)15-30 dias',
  '(PDD Total)30-60 dias',
  '(PDD Total)60-90 dias',
  '(PDD Total)90-120 dias',
  '(PDD Total)120-150 dias',
  '(PDD Total)150-180 dias',
  '(PDD Total)180-999 dias',
  'Cedente 1',
  'Cedente 2',
  'Cedente 3',
  'Cedente 4',
  'Cedente 5',
  'Cedente 6',
  'Cedente 7',
  'Cedente 8',
  'Cedente 9',
  'Cedente 10',
  'Sacado 1',
  'Sacado 2',
  'Sacado 3',
  'Sacado 4',
  'Sacado 5',
  'Sacado 6',
  'Sacado 7',
  'Sacado 8',
  'Sacado 9',
  'Sacado 10'],
 'APPALOOSA': ['PL Total',
  'PL Sênior',
  'PL Mezanino',
  'PL Subordinada Jr',
  'Volume Operado',
  'Carteira (Direitos Creditórios)',
  'Caixa/Disponibilidades',
  'Quantidade de Cedentes',
  'Quantidade de Sacados',
  'Ticket Médio',
  'Taxa Média',
  'Prazo Médio',
  'Duplicata',
  'Cheques',
  'Contrato',
  'Nota Promissória',
  'CCB',
  'Nota Comercial',
  'Vencidos Total',
  'PDD Total',
  'PDD À Vencer',
  'Liquidado Total(R$)',
  'Recompra (R$)',
  'Concentração Top 10 Cedentes (R$)',
  'Concentração Top 10 Sacados (R$)',
  '(Vencidos Total)0-15 dias',
  '(Vencidos Total)15-30 dias',
  '(Vencidos Total)30-60 dias',
  '(Vencidos Total)60-90 dias',
  '(Vencidos Total)90-120 dias',
  '(Vencidos Total)120-150 dias',
  '(Vencidos Total)150-180 dias',
  '(Vencidos Total)180-999 dias',
  '(PDD Total)0-15 dias',
  '(PDD Total)15-30 dias',
  '(PDD Total)30-60 dias',
  '(PDD Total)60-90 dias',
  '(PDD Total)90-120 dias',
  '(PDD Total)120-150 dias',
  '(PDD Total)150-180 dias',
  '(PDD Total)180-999 dias',
  'Cedente 1',
  'Cedente 2',
  'Cedente 3',
  'Cedente 4',
  'Cedente 5',
  'Cedente 6',
  'Cedente 7',
  'Cedente 8',
  'Cedente 9',
  'Cedente 10',
  'Sacado 1',
  'Sacado 2',
  'Sacado 3',
  'Sacado 4',
  'Sacado 5',
  'Sacado 6',
  'Sacado 7',
  'Sacado 8',
  'Sacado 9',
  'Sacado 10'],
 'ARTICO': ['PL Total',
  'PL Sênior',
  'PL Mezanino',
  'PL Subordinada Jr',
  'Carteira (Direitos Creditórios)',
  'Caixa/Disponibilidades',
  'Quantidade de Cedentes',
  'Quantidade de Sacados',
  'Ticket Médio',
  'Taxa Média',
  'Prazo Médio',
  'CCB',
  'Cheques',
  'Confissão de Dívida',
  'Contrato',
  'Duplicata',
  'Nota Comercial',
  'Nota Promissória',
  'Vencidos Total',
  'PDD Total',
  'PDD À Vencer',
  'Concentração Top 10 Cedentes (R$)',
  'Concentração Top 10 Sacados (R$)',
  'Volume Operado',
  'Recompra (R$)',
  'Liquidado Total(R$)',
  'Liquidado Antecipadamente',
  'Liquidado no Prazo',
  'Entre D1-D15',
  'Entre D16-D30',
  'Entre D31-D90',
  'Entre D91-D120',
  'Acima de D120',
  'Retorno Cota Subordinada',
  '(Vencidos Total)0-30 dias',
  '(Vencidos Total)30-60 dias',
  '(Vencidos Total)60-90 dias',
  '(Vencidos Total)90-120 dias',
  '(Vencidos Total)> 120 dias',
  '(PDD Total)0-30 dias',
  '(PDD Total)30-60 dias',
  '(PDD Total)60-90 dias',
  '(PDD Total)90-120 dias',
  '(PDD Total)> 120 dias',
  'Cedente 1',
  'Cedente 2',
  'Cedente 3',
  'Cedente 4',
  'Cedente 5',
  'Cedente 6',
  'Cedente 7',
  'Cedente 8',
  'Cedente 9',
  'Cedente 10',
  'Sacado 1',
  'Sacado 2',
  'Sacado 3',
  'Sacado 4',
  'Sacado 5',
  'Sacado 6',
  'Sacado 7',
  'Sacado 8',
  'Sacado 9',
  'Sacado 10'],
 'BARCELONA': ['PL Total',
  'PL Sênior',
  'PL Mezanino',
  'PL Subordinada Jr',
  'Carteira (Direitos Creditórios)',
  'Caixa/Disponibilidades',
  'Quantidade de Cedentes',
  'Quantidade de Sacados',
  'Ticket Médio',
  'Taxa Média',
  'Prazo Médio',
  'Cheques',
  'Confissão de Dívida',
  'Contrato',
  'Duplicata',
  'Duplicata de Serviço Físico',
  'CCB',
  'Nota Promissória',
  'Nota Comercial',
  'Vencidos Total',
  'PDD Total',
  'PDD À Vencer',
  'Liquidado Total(R$)',
  'Recompra (R$)',
  'Concentração Top 10 Cedentes (R$)',
  'Concentração Top 10 Sacados (R$)',
  'Retorno Cota Subordinada',
  '(Vencidos Total)0-15 dias',
  '(Vencidos Total)15-30 dias',
  '(Vencidos Total)30-60 dias',
  '(Vencidos Total)60-90 dias',
  '(Vencidos Total)90-120 dias',
  '(Vencidos Total)120-150 dias',
  '(Vencidos Total)150-180 dias',
  '(Vencidos Total)180-999 dias',
  '(PDD Total)0-15 dias',
  '(PDD Total)15-30 dias',
  '(PDD Total)30-60 dias',
  '(PDD Total)60-90 dias',
  '(PDD Total)90-120 dias',
  '(PDD Total)120-150 dias',
  '(PDD Total)150-180 dias',
  '(PDD Total)180-999 dias',
  'Cedente 1',
  'Cedente 2',
  'Cedente 3',
  'Cedente 4',
  'Cedente 5',
  'Cedente 6',
  'Cedente 7',
  'Cedente 8',
  'Cedente 9',
  'Cedente 10',
  'Sacado 1',
  'Sacado 2',
  'Sacado 3',
  'Sacado 4',
  'Sacado 5',
  'Sacado 6',
  'Sacado 7',
  'Sacado 8',
  'Sacado 9',
  'Sacado 10'],
 'MULTIASSET': ['PL Total',
  'PL Sênior',
  'PL Mezanino',
  'PL Subordinada Jr',
  'Retorno Cota Subordinada',
  'Resgates Sênior',
  'Resgates Subordinada Mezanino',
  'Resgates Subordinada Jr.',
  'Carteira (Direitos Creditórios)',
  'Caixa/Disponibilidades',
  'Vencidos Total',
  'PDD Total',
  'Ticket Médio',
  'Prazo Médio',
  'Taxa Média',
  'Volume Operado',
  'Duplicata',
  'Contrato',
  'Cheques',
  'Nota Promissória',
  'Liquidado Total(R$)',
  'Liquidado Vencido',
  'Liquidado Antecipadamente',
  'Liquidado no Prazo',
  'Entre D1-D5',
  'Entre D6-D15',
  'Entre D16-D30',
  'Acima de D30',
  'Recompra (R$)',
  'Quantidade de Cedentes',
  'Concentração Top 10 Cedentes (R$)',
  'Quantidade de Sacados',
  'Concentração Top 10 Sacados (R$)',
  'Cedente 1',
  'Cedente 2',
  'Cedente 3',
  'Cedente 4',
  'Cedente 5',
  'Cedente 6',
  'Cedente 7',
  'Cedente 8',
  'Cedente 9',
  'Cedente 10',
  'Sacado 1',
  'Sacado 2',
  'Sacado 3',
  'Sacado 4',
  'Sacado 5',
  'Sacado 6',
  'Sacado 7',
  'Sacado 8',
  'Sacado 9',
  'Sacado 10'],
 'MULTIPLIKE': ['PL Total',
  'PL Sênior',
  'PL Mezanino',
  'PL Subordinada Jr',
  'Carteira (Direitos Creditórios)',
  'Duplicata',
  'Contrato',
  'Cheques',
  'Caixa/Disponibilidades',
  'Taxa Média',
  'Prazo Médio',
  'Volume Operado',
  'Vencidos Total',
  'PDD Total',
  'Recompra (R$)',
  'Liquidado Total(R$)',
  'Retorno Cota Subordinada',
  'Número de Funcionários',
  'Concentração Top 10 Sacados (R$)',
  'Concentração Top 10 Cedentes (R$)',
  '(Vencidos Total)0-5 dias',
  '(Vencidos Total)5-30 dias',
  '(Vencidos Total)30-60 dias',
  '(Vencidos Total)60-90 dias',
  '(Vencidos Total)90-120 dias',
  '(Vencidos Total)> 120 dias',
  '(PDD Total)0-5 dias',
  '(PDD Total)5-30 dias',
  '(PDD Total)30-60 dias',
  '(PDD Total)60-90 dias',
  '(PDD Total)90-120 dias',
  '(PDD Total)> 120 dias',
  'Cedente 1',
  'Cedente 2',
  'Cedente 3',
  'Cedente 4',
  'Cedente 5',
  'Cedente 6',
  'Cedente 7',
  'Cedente 8',
  'Cedente 9',
  'Cedente 10',
  'Sacado 1',
  'Sacado 2',
  'Sacado 3',
  'Sacado 4',
  'Sacado 5',
  'Sacado 6',
  'Sacado 7',
  'Sacado 8',
  'Sacado 9',
  'Sacado 10'],
 'ONE7': ['PL Total',
  'PL Sênior',
  'PL Mezanino',
  'PL Subordinada Jr',
  'Carteira (Direitos Creditórios)',
  'Quantidade de Cedentes',
  'Quantidade de Sacados',
  'Ticket Médio',
  'Taxa Média',
  'Prazo Médio',
  'Cheques',
  'Confissão de Dívida',
  'Contrato',
  'Duplicata',
  'Duplicata de Serviço Físico',
  'Vencidos Total',
  'PDD Total',
  'PDD À Vencer',
  'Recompra (R$)',
  'Retorno Cota Subordinada',
  'Número de Funcionários',
  'Concentração Top 10 Sacados (R$)',
  'Concentração Top 10 Cedentes (R$)',
  '(Vencidos Total)0-15 dias',
  '(Vencidos Total)15-30 dias',
  '(Vencidos Total)30-60 dias',
  '(Vencidos Total)60-90 dias',
  '(Vencidos Total)90-120 dias',
  '(PDD Total)0-15 dias',
  '(PDD Total)15-30 dias',
  '(PDD Total)30-60 dias',
  '(PDD Total)60-90 dias',
  '(PDD Total)90-120 dias',
  '(PDD Total)120-150 dias',
  '(PDD Total)150-180 dias',
  '(PDD Total)180-360 dias',
  'Cedente 1',
  'Cedente 2',
  'Cedente 3',
  'Cedente 4',
  'Cedente 5',
  'Cedente 6',
  'Cedente 7',
  'Cedente 8',
  'Cedente 9',
  'Cedente 10',
  'Sacado 1',
  'Sacado 2',
  'Sacado 3',
  'Sacado 4',
  'Sacado 5',
  'Sacado 6',
  'Sacado 7',
  'Sacado 8',
  'Sacado 9',
  'Sacado 10'],
 'PAGOL': ['PL Total',
  'PL Sênior',
  'PL Mezanino',
  'PL Subordinada Jr',
  'Retorno Cota Subordinada',
  'Resgates Subordinada Mezanino',
  'Resgates Subordinada Jr.',
  'Carteira (Direitos Creditórios)',
  'Caixa/Disponibilidades',
  'Vencidos Total',
  'PDD Total',
  'Ticket Médio',
  'Prazo Médio',
  'Taxa Média',
  'Volume Operado',
  'Duplicata',
  'Contrato',
  'CCB',
  'Cheques',
  'Liquidado Antecipadamente',
  'Liquidado no Prazo',
  'Entre D1-D5',
  'Entre D6-D15',
  'Entre D16-D30',
  'Acima de D30',
  'Recompra (R$)',
  'Quantidade de Cedentes',
  'Concentração Top 10 Cedentes (R$)',
  'Quantidade de Sacados',
  'Concentração Top 10 Sacados (R$)',
  'Cedente 1',
  'Cedente 2',
  'Cedente 3',
  'Cedente 4',
  'Cedente 5',
  'Cedente 6',
  'Cedente 7',
  'Cedente 8',
  'Cedente 9',
  'Cedente 10',
  'Sacado 1',
  'Sacado 2',
  'Sacado 3',
  'Sacado 4',
  'Sacado 5',
  'Sacado 6',
  'Sacado 7',
  'Sacado 8',
  'Sacado 9',
  'Sacado 10'],
 'PHD': ['PL Total',
  'PL Sênior',
  'PL Mezanino',
  'PL Subordinada Jr',
  'Resgates Sênior',
  'Resgates Subordinada Mezanino',
  'Resgates Subordinada Jr.',
  'Caixa/Disponibilidades',
  'Volume Operado',
  'Quantidade de Cedentes',
  'Quantidade de Sacados',
  'Taxa Média',
  'Prazo Médio',
  'Retorno Cota Subordinada',
  'Liquidado Total(R$)',
  'Recompra (R$)',
  'Carteira (Direitos Creditórios)',
  'Duplicata',
  'Cheques',
  'Duplicata de Serviço Físico',
  'Contrato',
  'Confissão de Dívida',
  'Nota Comercial',
  'CCB',
  'Vencidos Total',
  'PDD Total',
  'PDD À Vencer',
  'Concentração Top 10 Cedentes (R$)',
  'Concentração Top 10 Sacados (R$)',
  '(Vencidos Total)15-30 dias',
  '(Vencidos Total)30-60 dias',
  '(Vencidos Total)60-90 dias',
  '(Vencidos Total)90-120 dias',
  '(Vencidos Total)120-150 dias',
  '(Vencidos Total)150-180 dias',
  '(Vencidos Total)180-365 dias',
  '(PDD Total)15-30 dias',
  '(PDD Total)30-60 dias',
  '(PDD Total)60-90 dias',
  '(PDD Total)90-120 dias',
  '(PDD Total)120-150 dias',
  '(PDD Total)150-180 dias',
  '(PDD Total)180-365 dias',
  'Cedente 1',
  'Cedente 2',
  'Cedente 3',
  'Cedente 4',
  'Cedente 5',
  'Cedente 6',
  'Cedente 7',
  'Cedente 8',
  'Cedente 9',
  'Cedente 10',
  'Sacado 1',
  'Sacado 2',
  'Sacado 3',
  'Sacado 4',
  'Sacado 5',
  'Sacado 6',
  'Sacado 7',
  'Sacado 8',
  'Sacado 9',
  'Sacado 10'],
 'SOLAR': ['PL Sênior',
  'PL Mezanino',
  'PL Subordinada Jr',
  'PL Total',
  'Vencidos Total',
  'PDD Total',
  'Carteira (Direitos Creditórios)',
  'Quantidade de Cedentes',
  'Quantidade de Sacados',
  'Caixa/Disponibilidades',
  'Volume Operado',
  'Taxa Média',
  'Prazo Médio',
  'Liquidado Total(R$)',
  'Liquidado no Prazo',
  'Liquidado Antecipadamente',
  'Liquidado Vencido',
  'Recompra (R$)',
  'Concentração Top 10 Sacados (R$)',
  'Concentração Top 10 Cedentes (R$)',
  'Cedente 1',
  'Cedente 2',
  'Cedente 3',
  'Cedente 4',
  'Cedente 5',
  'Cedente 6',
  'Cedente 7',
  'Cedente 8',
  'Cedente 9',
  'Cedente 10',
  'Sacado 1',
  'Sacado 2',
  'Sacado 3',
  'Sacado 4',
  'Sacado 5',
  'Sacado 6',
  'Sacado 7',
  'Sacado 8',
  'Sacado 9',
  'Sacado 10']}

In [211]:
colunas_equivalentes.keys()

dict_keys(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Carteira (Direitos Creditórios)', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Caixa/Disponibilidades', 'Taxa Média', 'Prazo Médio', 'Ticket Médio', 'Retorno Cota Subordinada', 'Cheques', 'Duplicata', 'Duplicata de Serviço Físico', 'Contrato', 'Nota Comercial', 'Confissão de Dívida', 'Nota Promissória', 'CCB', 'Resgates Subordinada Jr.', 'Resgates Subordinada Mezanino', 'Resgates Sênior', 'Vencidos Total', 'PDD Total', 'PDD À Vencer', 'Liquidado Total(R$)', 'Liquidado Antecipadamente', 'Liquidado no Prazo', 'Liquidado Vencido', 'Entre D1-D5', 'Entre D1-D15', 'Entre D6-D15', 'Entre D16-D30', 'Acima de D30', 'Entre D31-D90', 'Entre D91-D120', 'Acima de D120', 'Recompra (R$)', 'Concentração Top 10 Cedentes (R$)', 'Concentração Top 10 Sacados (R$)', 'Número de Funcionários', 'Volume Operado'])

In [234]:
def selecionando_colunas_final(csv_dict, colunas):
    for key in csv_dict.keys():
        csv_dict[key] = csv_dict[key][colunas[key]]
    return csv_dict

print(resultado)
teste_final = selecionando_colunas_final(csv_dict, resultado)
print(teste_final)

{'ALFA': ['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Carteira (Direitos Creditórios)', 'Duplicata', 'Cheques', 'Caixa/Disponibilidades', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Taxa Média', 'Prazo Médio', 'Volume Operado', 'Liquidado Total(R$)', 'Vencidos Total', 'PDD Total', 'PDD À Vencer', 'Recompra (R$)', 'Retorno Cota Subordinada', 'Número de Funcionários', 'Concentração Top 10 Sacados (R$)', 'Concentração Top 10 Cedentes (R$)', '(Vencidos Total)0-15 dias', '(Vencidos Total)15-30 dias', '(Vencidos Total)30-60 dias', '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias', '(Vencidos Total)120-150 dias', '(Vencidos Total)150-180 dias', '(Vencidos Total)180-999 dias', '(PDD Total)0-15 dias', '(PDD Total)15-30 dias', '(PDD Total)30-60 dias', '(PDD Total)60-90 dias', '(PDD Total)90-120 dias', '(PDD Total)120-150 dias', '(PDD Total)150-180 dias', '(PDD Total)180-999 dias', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10'], 'APPALOOSA': ['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Volume Operado', 'Carteira (Direitos Creditórios)', 'Caixa/Disponibilidades', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Ticket Médio', 'Taxa Média', 'Prazo Médio', 'Duplicata', 'Cheques', 'Contrato', 'Nota Promissória', 'CCB', 'Nota Comercial', 'Vencidos Total', 'PDD Total', 'PDD À Vencer', 'Liquidado Total(R$)', 'Recompra (R$)', 'Concentração Top 10 Cedentes (R$)', 'Concentração Top 10 Sacados (R$)', '(Vencidos Total)0-15 dias', '(Vencidos Total)15-30 dias', '(Vencidos Total)30-60 dias', '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias', '(Vencidos Total)120-150 dias', '(Vencidos Total)150-180 dias', '(Vencidos Total)180-999 dias', '(PDD Total)0-15 dias', '(PDD Total)15-30 dias', '(PDD Total)30-60 dias', '(PDD Total)60-90 dias', '(PDD Total)90-120 dias', '(PDD Total)120-150 dias', '(PDD Total)150-180 dias', '(PDD Total)180-999 dias', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10'], 'ARTICO': ['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Carteira (Direitos Creditórios)', 'Caixa/Disponibilidades', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Ticket Médio', 'Taxa Média', 'Prazo Médio', 'CCB', 'Cheques', 'Confissão de Dívida', 'Contrato', 'Duplicata', 'Nota Comercial', 'Nota Promissória', 'Vencidos Total', 'PDD Total', 'PDD À Vencer', 'Concentração Top 10 Cedentes (R$)', 'Concentração Top 10 Sacados (R$)', 'Volume Operado', 'Recompra (R$)', 'Liquidado Total(R$)', 'Liquidado Antecipadamente', 'Liquidado no Prazo', 'Entre D1-D15', 'Entre D16-D30', 'Entre D31-D90', 'Entre D91-D120', 'Acima de D120', 'Retorno Cota Subordinada', '(Vencidos Total)0-30 dias', '(Vencidos Total)30-60 dias', '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias', '(Vencidos Total)> 120 dias', '(PDD Total)0-30 dias', '(PDD Total)30-60 dias', '(PDD Total)60-90 dias', '(PDD Total)90-120 dias', '(PDD Total)> 120 dias', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10'], 'BARCELONA': ['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Carteira (Direitos Creditórios)', 'Caixa/Disponibilidades', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Ticket Médio', 'Taxa Média', 'Prazo Médio', 'Cheques', 'Confissão de Dívida', 'Contrato', 'Duplicata', 'Duplicata de Serviço Físico', 'CCB', 'Nota Promissória', 'Nota Comercial', 'Vencidos Total', 'PDD Total', 'PDD À Vencer', 'Liquidado Total(R$)', 'Recompra (R$)', 'Concentração Top 10 Cedentes (R$)', 'Concentração Top 10 Sacados (R$)', 'Retorno Cota Subordinada', '(Vencidos Total)0-15 dias', '(Vencidos Total)15-30 dias', '(Vencidos Total)30-60 dias', '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias', '(Vencidos Total)120-150 dias', '(Vencidos Total)150-180 dias', '(Vencidos Total)180-999 dias', '(PDD Total)0-15 dias', '(PDD Total)15-30 dias', '(PDD Total)30-60 dias', '(PDD Total)60-90 dias', '(PDD Total)90-120 dias', '(PDD Total)120-150 dias', '(PDD Total)150-180 dias', '(PDD Total)180-999 dias', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10'], 'MULTIASSET': ['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Retorno Cota Subordinada', 'Resgates Sênior', 'Resgates Subordinada Mezanino', 'Resgates Subordinada Jr.', 'Carteira (Direitos Creditórios)', 'Caixa/Disponibilidades', 'Vencidos Total', 'PDD Total', 'Ticket Médio', 'Prazo Médio', 'Taxa Média', 'Volume Operado', 'Duplicata', 'Contrato', 'Cheques', 'Nota Promissória', 'Liquidado Total(R$)', 'Liquidado Vencido', 'Liquidado Antecipadamente', 'Liquidado no Prazo', 'Entre D1-D5', 'Entre D6-D15', 'Entre D16-D30', 'Acima de D30', 'Recompra (R$)', 'Quantidade de Cedentes', 'Concentração Top 10 Cedentes (R$)', 'Quantidade de Sacados', 'Concentração Top 10 Sacados (R$)', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10'], 'MULTIPLIKE': ['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Carteira (Direitos Creditórios)', 'Duplicata', 'Contrato', 'Cheques', 'Caixa/Disponibilidades', 'Taxa Média', 'Prazo Médio', 'Volume Operado', 'Vencidos Total', 'PDD Total', 'Recompra (R$)', 'Liquidado Total(R$)', 'Retorno Cota Subordinada', 'Número de Funcionários', 'Concentração Top 10 Sacados (R$)', 'Concentração Top 10 Cedentes (R$)', '(Vencidos Total)0-5 dias', '(Vencidos Total)5-30 dias', '(Vencidos Total)30-60 dias', '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias', '(Vencidos Total)> 120 dias', '(PDD Total)0-5 dias', '(PDD Total)5-30 dias', '(PDD Total)30-60 dias', '(PDD Total)60-90 dias', '(PDD Total)90-120 dias', '(PDD Total)> 120 dias', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10'], 'ONE7': ['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Carteira (Direitos Creditórios)', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Ticket Médio', 'Taxa Média', 'Prazo Médio', 'Cheques', 'Confissão de Dívida', 'Contrato', 'Duplicata', 'Duplicata de Serviço Físico', 'Vencidos Total', 'PDD Total', 'PDD À Vencer', 'Recompra (R$)', 'Retorno Cota Subordinada', 'Número de Funcionários', 'Concentração Top 10 Sacados (R$)', 'Concentração Top 10 Cedentes (R$)', '(Vencidos Total)0-15 dias', '(Vencidos Total)15-30 dias', '(Vencidos Total)30-60 dias', '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias', '(PDD Total)0-15 dias', '(PDD Total)15-30 dias', '(PDD Total)30-60 dias', '(PDD Total)60-90 dias', '(PDD Total)90-120 dias', '(PDD Total)120-150 dias', '(PDD Total)150-180 dias', '(PDD Total)180-360 dias', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10'], 'PAGOL': ['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Retorno Cota Subordinada', 'Resgates Subordinada Mezanino', 'Resgates Subordinada Jr.', 'Carteira (Direitos Creditórios)', 'Caixa/Disponibilidades', 'Vencidos Total', 'PDD Total', 'Ticket Médio', 'Prazo Médio', 'Taxa Média', 'Volume Operado', 'Duplicata', 'Contrato', 'CCB', 'Cheques', 'Liquidado Antecipadamente', 'Liquidado no Prazo', 'Entre D1-D5', 'Entre D6-D15', 'Entre D16-D30', 'Acima de D30', 'Recompra (R$)', 'Quantidade de Cedentes', 'Concentração Top 10 Cedentes (R$)', 'Quantidade de Sacados', 'Concentração Top 10 Sacados (R$)', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10'], 'PHD': ['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Resgates Sênior', 'Resgates Subordinada Mezanino', 'Resgates Subordinada Jr.', 'Caixa/Disponibilidades', 'Volume Operado', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Taxa Média', 'Prazo Médio', 'Retorno Cota Subordinada', 'Liquidado Total(R$)', 'Recompra (R$)', 'Carteira (Direitos Creditórios)', 'Duplicata', 'Cheques', 'Duplicata de Serviço Físico', 'Contrato', 'Confissão de Dívida', 'Nota Comercial', 'CCB', 'Vencidos Total', 'PDD Total', 'PDD À Vencer', 'Concentração Top 10 Cedentes (R$)', 'Concentração Top 10 Sacados (R$)', '(Vencidos Total)15-30 dias', '(Vencidos Total)30-60 dias', '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias', '(Vencidos Total)120-150 dias', '(Vencidos Total)150-180 dias', '(Vencidos Total)180-365 dias', '(PDD Total)15-30 dias', '(PDD Total)30-60 dias', '(PDD Total)60-90 dias', '(PDD Total)90-120 dias', '(PDD Total)120-150 dias', '(PDD Total)150-180 dias', '(PDD Total)180-365 dias', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10'], 'SOLAR': ['PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'PL Total', 'Vencidos Total', 'PDD Total', 'Carteira (Direitos Creditórios)', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Caixa/Disponibilidades', 'Volume Operado', 'Taxa Média', 'Prazo Médio', 'Liquidado Total(R$)', 'Liquidado no Prazo', 'Liquidado Antecipadamente', 'Liquidado Vencido', 'Recompra (R$)', 'Concentração Top 10 Sacados (R$)', 'Concentração Top 10 Cedentes (R$)', 'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5', 'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10', 'Sacado 1', 'Sacado 2', 'Sacado 3', 'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9', 'Sacado 10']}
{'ALFA':                PL Total    PL Sênior  PL Mezanino  PL Subordinada Jr  \
Data
2021-02-28  45024572.58  11114979.71         0.00        33909592.87
2021-03-31  45335482.70  11054555.43         0.00        34280927.27
2021-04-30  42157354.56  11101101.48         0.00        31056253.08
2021-05-31  42599964.11  11155983.78         0.00        31443980.33
2021-06-30  42604290.52  11077437.32         0.00        31526853.20
2021-07-30  43097471.86  11143660.32         0.00        31953811.54
2021-08-31  43698279.89  11218383.15         0.00        32479896.74
2021-09-30  41415855.88  11115812.77         0.00        30300043.11
2021-10-29  41889150.23  11194731.71         0.00        30694418.52
2021-11-30  42063661.70  11286854.08         0.00        30776807.62
2021-12-31  42513837.23  11180814.12         0.00        31333023.11
2022-01-31  43094265.29  11291242.81         0.00        31803022.48
2022-02-25  43365748.05  11402569.91         0.00        31963178.14
2022-03-31  45957517.39  13402905.56         0.00        32554611.83
2022-04-30  50289651.51  17434242.33         0.00        32855409.18
2022-05-31  56146978.38  22695941.14         0.00        33451037.24
2022-06-01  56800902.22  23163002.26         0.00        33637899.96
2022-07-01  58708845.34  24647581.61         0.00        34061263.73
2022-08-31  59845087.39  25341070.54         0.00        34504016.85
2022-09-30  60534611.25  25512129.24         0.00        35022482.01
2022-10-31  60764388.70  25445396.83         0.00        35318991.87
2022-11-30  58486031.05  25797787.07         0.00        32688243.98
2022-12-31  59096683.24  25791529.88         0.00        33305153.36
2023-01-01  57689309.73  25708150.25         0.00        31981159.48
2023-02-01  58334369.70  26028427.54         0.00        32305942.16
2023-03-01  59984394.36  27040188.20         0.00        32944206.16
2023-04-01  61168626.94  27876089.46         0.00        33292537.48
2023-05-01  62518881.57  28301830.66   1003512.97        33213537.94
2023-06-01  63275648.74  28321333.94   1018402.72        33935912.08
2023-07-01  63516938.23  28186150.30   1033513.41        34297274.52
2023-08-01  64333599.12  28626110.86   1049953.10        34657535.16
2023-09-01  65266870.63  28595403.45   1064300.08        35607167.10
2023-10-01  65617248.99  28247814.10   1079296.58        36290138.31
2023-11-01  61509778.44  23776679.07   1093427.89        36639671.48
2023-12-01  62689150.59  24035638.83   1107508.72        37546003.04
2024-01-01  58330205.65  23867501.87   1122988.11        33339715.67
2024-02-01  59214428.87  24142653.01   1136166.36        33935609.50
2024-03-01  59672982.82  24222058.46   1150080.86        34300843.50
2024-04-01  59743330.22  24044928.53   1165239.68        34533162.01
2024-05-01  53756094.80  18432684.14   1179736.96        34143673.70
2024-06-01  54984385.19  18645813.67   1193650.32        35144921.20
2024-07-01  54929878.96  18419803.13   1209853.66        35300222.17
2024-08-01  53519605.59  18654101.44   1225558.29        33639945.86
2024-09-30  54547705.48  18881869.69   1240817.15        34425018.64
2024-10-31  54595552.03  18649109.58   1257920.43        34688522.02
2024-11-30  55554517.29  18862675.95   1272545.61        35419295.73
2024-12-30  55494249.83  19112922.92   1289585.52        35091741.39
2025-01-31  53029260.06  18899014.18   1308166.02        32822079.86
2025-02-28  52152511.28  19159589.71         0.00        32992921.57
2025-03-31  52499921.56  19415845.20         0.00        33084076.36
2025-04-30  55985062.10  21991907.43         0.00        33993154.67

            Carteira (Direitos Creditórios)    Duplicata     Cheques  \
Data
2021-02-28                     4.680848e+07          NaN         NaN
2021-03-31                     4.419317e+07          NaN         NaN
2021-04-30                     4.301425e+07          NaN         NaN
2021-05-31                     3.964672e+07          NaN         NaN
2021-06-30                     3.906523e+07          NaN         NaN
2021-07-30                     3.988348e+07          NaN         NaN
2021-08-31                     4.029169e+07          NaN         NaN
2021-09-30                     4.019774e+07          NaN         NaN
2021-10-29                     4.097018e+07          NaN         NaN
2021-11-30                     4.044490e+07          NaN         NaN
2021-12-31                     4.180005e+07          NaN         NaN
2022-01-31                     4.120462e+07          NaN         NaN
2022-02-25                     4.343140e+07          NaN         NaN
2022-03-31                     4.590163e+07          NaN         NaN
2022-04-30                     4.929485e+07          NaN         NaN
2022-05-31                     5.126824e+07          NaN         NaN
2022-06-01                     5.200396e+07          NaN         NaN
2022-07-01                     5.804898e+07          NaN         NaN
2022-08-31                     5.540443e+07          NaN         NaN
2022-09-30                     5.572313e+07          NaN         NaN
2022-10-31                     5.928764e+07          NaN         NaN
2022-11-30                     5.829984e+07          NaN         NaN
2022-12-31                     5.402264e+07  50929462.87  6872775.66
2023-01-01                     5.255689e+07  49978336.25  6302040.27
2023-02-01                     5.427531e+07  51675932.52  5662013.65
2023-03-01                     5.937295e+07  56930728.76  5337720.70
2023-04-01                     5.962838e+07  55558876.35  5937889.67
2023-05-01                     6.078110e+07  58901171.27  4733195.23
2023-06-01                     5.903945e+07  58949150.75  4861258.89
2023-07-01                     6.123429e+07  58080960.56  5210833.53
2023-08-01                     5.978432e+07  58105517.49  4433487.47
2023-09-01                     5.880317e+07  58471431.47  4718464.99
2023-10-01                     6.014476e+07  59151079.01  3897076.96
2023-11-01                     5.663013e+07  57571023.95  2799138.10
2023-12-01                     5.727985e+07  59854198.41  2995593.91
2024-01-01                     5.616486e+07  59008709.98  2818319.79
2024-02-01                     5.288690e+07  53193914.22  3334459.96
2024-03-01                     5.184418e+07  53576664.50  3155846.96
2024-04-01                     4.892332e+07  52342525.47  2699841.98
2024-05-01                     5.010371e+07  55558544.67  2349718.05
2024-06-01                     4.965781e+07  55352838.32  2057826.85
2024-07-01                     5.042151e+07  55005223.69  2103687.65
2024-08-01                     4.978897e+07  53222499.31  2099647.74
2024-09-30                     4.917629e+07  52906197.07  1884358.69
2024-10-31                     5.290756e+07  52272045.43  1839127.34
2024-11-30                     4.985759e+07  50348708.73  2919897.08
2024-12-30                     4.784210e+07  48722823.07   293595.83
2025-01-31                     4.442206e+07  42807351.03  2871700.41
2025-02-28                     4.544952e+07  43968478.81  2953400.59
2025-03-31                     5.122216e+07  49395045.31  2917340.81
2025-04-30                     5.307486e+07  49583910.86  2723720.61

            Caixa/Disponibilidades  Quantidade de Cedentes  \
Data
2021-02-28               660791.01                   116.0
2021-03-31              2085139.84                   116.0
2021-04-30              1175828.31                   116.0
2021-05-31              1089187.05                   115.0
2021-06-30              1445235.01                   105.0
2021-07-30               588172.64                   105.0
2021-08-31               730150.25                   105.0
2021-09-30               539846.48                   101.0
2021-10-29               448301.78                   105.0
2021-11-30              1121538.61                   102.0
2021-12-31               775325.26                   102.0
2022-01-31               636307.21                   103.0
2022-02-25               370670.70                   111.0
2022-03-31                99196.68                   112.0
2022-04-30                39928.96                   116.0
2022-05-31               471365.55                   110.0
2022-06-01                97286.56                   106.0
2022-07-01               676010.24                   113.0
2022-08-31               670508.52                   113.0
2022-09-30               670508.52                   106.0
2022-10-31               357021.02                   105.0
2022-11-30               357021.02                   104.0
2022-12-31               130042.40                   103.0
2023-01-01               130042.40                   101.0
2023-02-01               369591.82                    82.0
2023-03-01               369591.82                    98.0
2023-04-01               365572.41                    95.0
2023-05-01               623287.66                    87.0
2023-06-01               248560.09                   105.0
2023-07-01               248560.09                   105.0
2023-08-01               292755.01                   103.0
2023-09-01               355424.65                   102.0
2023-10-01               345404.22                   104.0
2023-11-01               345404.22                   101.0

In [213]:
def juntar_por_data(csv_dict, data):
    lista_dados = []

    for key, df in csv_dict.items():
        if data in df.index:
            linha = df.loc[data]
            linha_df = pd.DataFrame([linha], index=[key])
        else:
            linha_df = pd.DataFrame([{col: pd.NA for col in df.columns}], index=[key])

        lista_dados.append(linha_df)

    resultado = pd.concat(lista_dados, axis=0, sort=True)
    return resultado

In [214]:
# checar dps esse Taxa Média Recebíveis Média ponderada

#o padrão vai ser "Prazo Médio"
# checar dps esse Prazo Médio Recebíveis Estoque (dias úteis) e Prazo médio aquisição no mês
# formatar todas de dias corridos para úteis, se for o caso
# oq não tem especificando é corrido

#remover recebíveis

# hoje a tarde fazer:
    # ajeitar TUDO do SOLAR
    # ajeitar todas as %
    # adicionar últimos dados gerais
    # ai dps disso eu vejo mais oq adicionar e também os q ficarão no fim do DF final
    # também tenho que lembrar que não dá pra unir tudo de uma vez então pensar em como fica a estrutura final
    #    - vou manter os dataframes PARSEADOS em CSV padronizados salvos separados
    #    - manter o planilhão por mês
    # ajeitar os 0-15 que importam, colocando os padrãozinho lá

In [215]:
def padronizar_indices_para_fim_do_mes(csv_dict):
    csv_dict_padronizado = {}

    for key, df in csv_dict.items():
        df = df.copy()

        # Garante que o índice está no formato datetime
        df.index = pd.to_datetime(df.index, errors='coerce')

        # Remove linhas com índice inválido (caso existam)
        df = df[~df.index.isna()]

        # Ajusta cada data para o último dia do mês
        df.index = df.index.to_period('M').to_timestamp('M')

        # Se houver duplicação após essa conversão, agrupar (aqui usamos média, mas pode ser alterado)
        df = df.groupby(df.index).first()

        csv_dict_padronizado[key] = df

    return csv_dict_padronizado

teste_final = padronizar_indices_para_fim_do_mes(teste_final)

In [216]:
resultado_quasefinal = juntar_por_data(teste_final, "2025-04-30")

In [217]:
def mostrar_colunas_repetidas(csv_dict):
    for key, df in csv_dict.items():
        colunas_repetidas = df.columns[df.columns.duplicated()]
        if len(colunas_repetidas) > 0:
            print(f'DataFrame "{key}" tem colunas repetidas:')
            print(colunas_repetidas.tolist())
        else:
            print(f'DataFrame "{key}" não tem colunas repetidas.')

# Exemplo de uso:
mostrar_colunas_repetidas(teste_final)

DataFrame "ALFA" não tem colunas repetidas.
DataFrame "APPALOOSA" não tem colunas repetidas.
DataFrame "ARTICO" não tem colunas repetidas.
DataFrame "BARCELONA" não tem colunas repetidas.
DataFrame "MULTIASSET" não tem colunas repetidas.
DataFrame "MULTIPLIKE" não tem colunas repetidas.
DataFrame "ONE7" não tem colunas repetidas.
DataFrame "PAGOL" não tem colunas repetidas.
DataFrame "PHD" não tem colunas repetidas.
DataFrame "SOLAR" não tem colunas repetidas.

In [218]:
teste_final.keys()

dict_keys(['ALFA', 'APPALOOSA', 'ARTICO', 'BARCELONA', 'MULTIASSET', 'MULTIPLIKE', 'ONE7', 'PAGOL', 'PHD', 'SOLAR'])

In [219]:
colunas_equivalentes.keys()

dict_keys(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr', 'Carteira (Direitos Creditórios)', 'Quantidade de Cedentes', 'Quantidade de Sacados', 'Caixa/Disponibilidades', 'Taxa Média', 'Prazo Médio', 'Ticket Médio', 'Retorno Cota Subordinada', 'Cheques', 'Duplicata', 'Duplicata de Serviço Físico', 'Contrato', 'Nota Comercial', 'Confissão de Dívida', 'Nota Promissória', 'CCB', 'Resgates Subordinada Jr.', 'Resgates Subordinada Mezanino', 'Resgates Sênior', 'Vencidos Total', 'PDD Total', 'PDD À Vencer', 'Liquidado Total(R$)', 'Liquidado Antecipadamente', 'Liquidado no Prazo', 'Liquidado Vencido', 'Entre D1-D5', 'Entre D1-D15', 'Entre D6-D15', 'Entre D16-D30', 'Acima de D30', 'Entre D31-D90', 'Entre D91-D120', 'Acima de D120', 'Recompra (R$)', 'Concentração Top 10 Cedentes (R$)', 'Concentração Top 10 Sacados (R$)', 'Número de Funcionários', 'Volume Operado'])

In [220]:
from itertools import chain

lista_unica = pd.Series(chain.from_iterable(list2.values()))

testeee = list(lista_unica.drop_duplicates())

In [221]:
def extrair_ordem(item):
    match = re.match(r'^\((.*?)\)\s*(>?=?\s*\d+)(?:\s*-\s*(\d+))?', item)
    if match:
        grupo = match.group(1)
        ini_raw = match.group(2)
        fim_raw = match.group(3)

        ini = int(re.sub(r'\D', '', ini_raw)) if ini_raw else 0
        fim = int(fim_raw) if fim_raw else (ini if '>' not in ini_raw else 9999)

        return (grupo, ini, fim)
    else:
        return ('ZZZ', 99999, 99999)  # Ficam no fim: 'Cedente', 'Sacado' etc.

In [222]:
# Ordenar
#lista_ordenada = sorted(testeee, key=extrair_ordem)

#lista_ordenada

In [223]:
lista_unica2 = list(colunas_equivalentes.keys())

#ordem_final = lista_unica2 +lista_ordenada

In [224]:
#ordem_final
# resolver problemas das colunas repetidas

In [225]:
import re

def organizar_colunas_df(lista_unica2, testeee):
    def extrair_ordem(item):
        match = re.match(r'^\((.*?)\)\s*(>?=?\s*\d+)(?:\s*-\s*(\d+))?', item)
        if match:
            grupo = match.group(1)
            ini_raw = match.group(2)
            fim_raw = match.group(3)

            ini = int(re.sub(r'\D', '', ini_raw)) if ini_raw else 0
            fim = int(fim_raw) if fim_raw else (ini if '>' not in ini_raw else 9999)

            return (grupo, ini, fim)
        else:
            return ('ZZZ', 99999, 99999)  # Para colunas fora do padrão

    # Ordena colunas do tipo (Grupo)X-Y dias
    lista_ordenada = sorted(testeee, key=extrair_ordem)
    resultado = lista_unica2 + lista_ordenada

    # Regras de reorganização
    if 'Concentração Top 10 Cedentes (R$)' in resultado and 'Cedente 1' in resultado:
        resultado.remove('Concentração Top 10 Cedentes (R$)')
        idx = resultado.index('Cedente 1')
        resultado.insert(idx, 'Concentração Top 10 Cedentes (R$)')

    if 'Concentração Top 10 Sacados (R$)' in resultado and 'Sacado 1' in resultado:
        resultado.remove('Concentração Top 10 Sacados (R$)')
        idx = resultado.index('Sacado 1')
        resultado.insert(idx, 'Concentração Top 10 Sacados (R$)')

    padrao_grupo = re.compile(r'^\(([^)]+)\)\s*[\d>]')
    grupos = {}
    for i, col in enumerate(resultado):
        match = padrao_grupo.match(col)
        if match:
            grupo = match.group(1)
            if grupo not in grupos and grupo in resultado:
                grupos[grupo] = i

    for grupo, idx_ref in grupos.items():
        if grupo in resultado:
            resultado.remove(grupo)
            resultado.insert(idx_ref - 1, grupo)

    # Mover 'PDD À Vencer' após último '(PDD Total)X-Y dias'
    if 'PDD À Vencer' in resultado:
        padrao_pdd = re.compile(r'^\(PDD Total\)\s*\d+\s*-\s*\d+\s*dias')
        indices_pdd = [i for i, col in enumerate(resultado) if padrao_pdd.match(col)]
        if indices_pdd:
            idx_destino = max(indices_pdd)
            resultado.remove('PDD À Vencer')
            resultado.insert(idx_destino, 'PDD À Vencer')

    return resultado

In [226]:
ordem_final = organizar_colunas_df(lista_unica2, testeee)

In [227]:
# valores dos tipos de ativos financeiros

resultado_quasefinal[ordem_final]

,PL Total,PL Sênior,PL Mezanino,PL Subordinada Jr,Carteira (Direitos Creditórios),Quantidade de Cedentes,Quantidade de Sacados,Caixa/Disponibilidades,Taxa Média,Prazo Médio,...,Sacado 1,Sacado 2,Sacado 3,Sacado 4,Sacado 5,Sacado 6,Sacado 7,Sacado 8,Sacado 9,Sacado 10
ALFA,5.598506e+07,2.199191e+07,0.000000e+00,3.399315e+07,5.307486e+07,82.0,3431.0,48438.44,0.022500,55.498530,...,1133381.51,904865.38,899158.06,876366.42,864658.07,838767.35,776919.78,755725.97,753557.34,749626.89
APPALOOSA,1.001210e+08,5.976211e+07,2.015185e+07,2.020706e+07,9.085485e+07,159.0,1795.0,12919151.00,0.024300,38.340000,...,2984199.11,2929089.24,2559215.76,2088988.89,2026239.89,1954596.66,1825106.54,1751017.27,1619262.22,1598968.32
ARTICO,2.698650e+08,1.576472e+08,4.759298e+07,6.462484e+07,2.362079e+08,84.0,1058.0,32158205.46,0.017219,87.000000,...,10961976.21,8207358.80,6790398.53,4117255.10,3477036.45,3452719.16,3252754.03,2898932.10,2450243.81,2146715.45
BARCELONA,9.827086e+07,4.823815e+07,1.717214e+07,3.286056e+07,9.147797e+07,175.0,4039.0,7428303.03,0.028800,45.600000,...,4322497.28,2801970.76,1911557.19,1859666.77,1824915.62,1290029.83,1254892.33,1218931.53,1212395.09,1014758.43
MULTIASSET,3.129984e+08,7.358007e+07,7.298921e+07,1.664291e+08,2.767261e+08,99.0,9649.0,1098.16,0.020900,151.050010,...,16506920.85,10563001.52,10299250.06,10233916.98,9079514.82,8296792.37,6801516.90,6718595.39,6627403.16,6442768.72
MULTIPLIKE,1.167739e+09,6.996966e+08,2.333193e+08,2.347235e+08,1.081891e+09,NaN,NaN,3578768.69,0.020100,92.510000,...,29060526.51,20876433.33,20050187.23,19536280.14,19260990.78,19140068.29,19050280.11,16759595.02,16332189.32,15430254.00
ONE7,2.795621e+08,1.576532e+08,2.217392e+07,9.973501e+07,2.701015e+08,763.0,6636.0,NaN,0.026800,23.780000,...,6276039.99,4413772.00,4197021.13,4089931.49,3450855.46,3339737.08,3192687.54,2993015.78,2758067.43,2683623.49
PAGOL,6.166202e+07,1.197339e+07,0.000000e+00,4.968863e+07,6.882882e+07,2.0,6610.0,5501335.77,0.016552,282.858882,...,86808.59,76511.01,75748.85,72991.80,67231.44,65691.88,65273.94,64372.18,63798.42,62905.78
PHD,1.829639e+08,1.092947e+08,3.633387e+07,3.733539e+07,1.693614e+08,154.0,6265.0,15861812.33,0.022974,129.136437,...,4106189.90,4082969.61,3915270.94,3269730.66,3216040.38,2919589.98,2871364.27,2632528.40,1834455.23,1737043.48
SOLAR,1.234262e+08,8.156198e+07,1.303532e+07,2.882895e+07,1.174088e+08,32.0,579.0,5637403.54,0.023876,28.902024,...,7076750.47,4992126.41,4050580.42,2958487.69,2807804.32,2672698.40,2535911.00,2401315.20,2174519.29,1808588.42

In [228]:
resultado_quasefinal[ordem_final].columns

Index(['PL Total', 'PL Sênior', 'PL Mezanino', 'PL Subordinada Jr',
       'Carteira (Direitos Creditórios)', 'Quantidade de Cedentes',
       'Quantidade de Sacados', 'Caixa/Disponibilidades', 'Taxa Média',
       'Prazo Médio', 'Ticket Médio', 'Retorno Cota Subordinada', 'Cheques',
       'Duplicata', 'Duplicata de Serviço Físico', 'Contrato',
       'Nota Comercial', 'Confissão de Dívida', 'Nota Promissória', 'CCB',
       'Resgates Subordinada Jr.', 'Resgates Subordinada Mezanino',
       'Resgates Sênior', 'Liquidado Total(R$)', 'Liquidado Antecipadamente',
       'Liquidado no Prazo', 'Liquidado Vencido', 'Entre D1-D5',
       'Entre D1-D15', 'Entre D6-D15', 'Entre D16-D30', 'Acima de D30',
       'Entre D31-D90', 'Entre D91-D120', 'Acima de D120', 'Recompra (R$)',
       'Número de Funcionários', 'Volume Operado', 'PDD Total',
       '(PDD Total)0-5 dias', '(PDD Total)0-15 dias', '(PDD Total)0-30 dias',
       '(PDD Total)5-30 dias', '(PDD Total)15-30 dias',
       '(PDD Total)30-60 dias', '(PDD Total)60-90 dias',
       '(PDD Total)90-120 dias', '(PDD Total)120-150 dias',
       '(PDD Total)> 120 dias', '(PDD Total)150-180 dias',
       '(PDD Total)180-360 dias', '(PDD Total)180-365 dias',
       '(PDD Total)180-999 dias', 'PDD À Vencer', 'Vencidos Total',
       '(Vencidos Total)0-5 dias', '(Vencidos Total)0-15 dias',
       '(Vencidos Total)0-30 dias', '(Vencidos Total)5-30 dias',
       '(Vencidos Total)15-30 dias', '(Vencidos Total)30-60 dias',
       '(Vencidos Total)60-90 dias', '(Vencidos Total)90-120 dias',
       '(Vencidos Total)120-150 dias', '(Vencidos Total)> 120 dias',
       '(Vencidos Total)150-180 dias', '(Vencidos Total)180-365 dias',
       '(Vencidos Total)180-999 dias', 'Concentração Top 10 Cedentes (R$)',
       'Cedente 1', 'Cedente 2', 'Cedente 3', 'Cedente 4', 'Cedente 5',
       'Cedente 6', 'Cedente 7', 'Cedente 8', 'Cedente 9', 'Cedente 10',
       'Concentração Top 10 Sacados (R$)', 'Sacado 1', 'Sacado 2', 'Sacado 3',
       'Sacado 4', 'Sacado 5', 'Sacado 6', 'Sacado 7', 'Sacado 8', 'Sacado 9',
       'Sacado 10'],
      dtype='object')

In [229]:
#checar tipos e informar algumas coisas depois

testeee

['(Vencidos Total)0-15 dias',
 '(Vencidos Total)15-30 dias',
 '(Vencidos Total)30-60 dias',
 '(Vencidos Total)60-90 dias',
 '(Vencidos Total)90-120 dias',
 '(Vencidos Total)120-150 dias',
 '(Vencidos Total)150-180 dias',
 '(Vencidos Total)180-999 dias',
 '(PDD Total)0-15 dias',
 '(PDD Total)15-30 dias',
 '(PDD Total)30-60 dias',
 '(PDD Total)60-90 dias',
 '(PDD Total)90-120 dias',
 '(PDD Total)120-150 dias',
 '(PDD Total)150-180 dias',
 '(PDD Total)180-999 dias',
 'Cedente 1',
 'Cedente 2',
 'Cedente 3',
 'Cedente 4',
 'Cedente 5',
 'Cedente 6',
 'Cedente 7',
 'Cedente 8',
 'Cedente 9',
 'Cedente 10',
 'Sacado 1',
 'Sacado 2',
 'Sacado 3',
 'Sacado 4',
 'Sacado 5',
 'Sacado 6',
 'Sacado 7',
 'Sacado 8',
 'Sacado 9',
 'Sacado 10',
 '(Vencidos Total)0-30 dias',
 '(Vencidos Total)> 120 dias',
 '(PDD Total)0-30 dias',
 '(PDD Total)> 120 dias',
 '(Vencidos Total)0-5 dias',
 '(Vencidos Total)5-30 dias',
 '(PDD Total)0-5 dias',
 '(PDD Total)5-30 dias',
 '(PDD Total)180-360 dias',
 '(Vencidos Total)180-365 dias',
 '(PDD Total)180-365 dias']

In [230]:
# o que preciso calcular:
    # (mezanino + junior) / total * 100
    # junior / total * 100
    # PDD / total * 100
    # Vencidos / total * 100
    # Liquidação / total * 100
    # Recompra / total * 100
    # Duplicatas / total * 100
    # Valor Total Operado / total * 100

In [231]:
resultado_quasefinal[ordem_final] = resultado_quasefinal[ordem_final].astype('float64')

In [232]:
df = resultado_quasefinal
col_total = "PL Total"
col_mezanino = "PL Mezanino"
col_junior = "PL Subordinada Jr"
col_pdd = "PDD Total"
col_vencidos = "Vencidos Total"
col_liquidacao = "Liquidado Total(R$)"
col_recompra = "Recompra (R$)"
col_duplicatas = "Duplicata"
col_valor_total_operado = "Volume Operado"

df_result = pd.DataFrame(index=df.index)

df_result["(Mezanino + Junior) / PL Total (%)"] = (df[col_mezanino].fillna(0) + df[col_junior].fillna(0)) / df[col_total] * 100
df_result["PL Subordinada Jr / PL Total (%)"] = df[col_junior] / df[col_total] * 100
df_result["PDD Total / PL Total (%)"] = df[col_pdd] / df[col_total] * 100
df_result["Vencidos Total / PL Total (%)"] = df[col_vencidos] / df[col_total] * 100
df_result["Liquidado Total(R$) / PL Total (%)"] = df[col_liquidacao] / df[col_total] * 100
df_result["Recompra (R$) / PL Total (%)"] = df[col_recompra] / df[col_total] * 100
df_result["Duplicata / PL Total (%)"] = df[col_duplicatas] / df[col_total] * 100
df_result["Volume Operado / PL Total (%)"] = df[col_valor_total_operado] / df[col_total] * 100

df_result

,(Mezanino + Junior) / PL Total (%),PL Subordinada Jr / PL Total (%),PDD Total / PL Total (%),Vencidos Total / PL Total (%),Liquidado Total(R$) / PL Total (%),Recompra (R$) / PL Total (%),Duplicata / PL Total (%),Volume Operado / PL Total (%)
ALFA,60.718258,60.718258,2.743012,7.894622,34.571699,1.599662,88.566323,49.612488
APPALOOSA,40.310130,20.182638,3.793427,3.717571,45.813403,2.326105,54.434369,39.058734
ARTICO,41.582944,23.947098,0.025490,1.613715,43.678885,1.162079,38.886182,50.490095
BARCELONA,50.913067,33.438769,7.537722,11.548592,55.195336,1.672575,63.191766,NaN
MULTIASSET,76.491867,53.172508,2.785524,6.403716,23.330749,3.448975,87.874480,24.656593
MULTIPLIKE,40.081104,20.100675,0.018631,3.505963,41.621353,0.613988,38.214505,41.316179
ONE7,43.607096,35.675435,5.077351,6.231930,NaN,8.370737,67.801518,NaN
PAGOL,80.582232,80.582232,20.482322,8.526370,NaN,0.000000,0.000000,0.233805
PHD,40.264357,20.405870,1.885314,9.014293,50.207870,2.062356,56.882198,51.738233
SOLAR,33.918450,23.357229,-0.323269,3.637098,22.717236,0.901507,NaN,25.306889