In [122]:
import pandas as pd

In [123]:
csv = []
for i in range(2, 5):
    csv.append(pd.read_csv(f'FIDCS_2025_0{i}_01.csv', delimiter=';'))

len(csv)

3

In [124]:
cols_to_verify = ["PL Total", "PL Sênior", "PL Subordinada Jr", "Subordinação (%)",
                  "Subordinação Jr (%)", "PDD Total (PL%)", "Vencidos Total (PL%)",
                  "Prazo Médio", "Taxa Média", "Concentração Maior Cedente (PL%)",
                  "Concentração Maior Sacado (PL%)", "Concentração 10 Maiores Cedentes (PL%)",
                  "Concentração 10 Maiores Sacados (PL%)", "Quantidade de Cedentes",
                  "Quantidade de Sacados", "Liquidados Total (PL%)", "Duplicata (PL%)",
                  "Recompra (PL%)", "Volume Operado (PL%)", "Caixa/Disponibilidades (%PL)"]

In [125]:
fidc = "SIFRAPLUS"

In [126]:
csv[0].loc[csv[0]["FIDC"] == fidc, cols_to_verify]

# Fev

,PL Total,PL Sênior,PL Subordinada Jr,Subordinação (%),Subordinação Jr (%),PDD Total (PL%),Vencidos Total (PL%),Prazo Médio,Taxa Média,Concentração Maior Cedente (PL%),Concentração Maior Sacado (PL%),Concentração 10 Maiores Cedentes (PL%),Concentração 10 Maiores Sacados (PL%),Quantidade de Cedentes,Quantidade de Sacados,Liquidados Total (PL%),Duplicata (PL%),Recompra (PL%),Volume Operado (PL%),Caixa/Disponibilidades (%PL)
21,9.413889e+08,5.394456e+08,2.925969e+08,42.696832,31.081402,2.701124,7.596936,NaN,NaN,5.575581,3.075537,33.248659,17.477694,341.0,10196.0,NaN,84.299351,0.570919,49.436773,7.948443

In [127]:
csv[1].loc[csv[1]["FIDC"] == fidc, cols_to_verify]

# Mar

,PL Total,PL Sênior,PL Subordinada Jr,Subordinação (%),Subordinação Jr (%),PDD Total (PL%),Vencidos Total (PL%),Prazo Médio,Taxa Média,Concentração Maior Cedente (PL%),Concentração Maior Sacado (PL%),Concentração 10 Maiores Cedentes (PL%),Concentração 10 Maiores Sacados (PL%),Quantidade de Cedentes,Quantidade de Sacados,Liquidados Total (PL%),Duplicata (PL%),Recompra (PL%),Volume Operado (PL%),Caixa/Disponibilidades (%PL)
20,9.535962e+08,5.458821e+08,2.970226e+08,42.755418,31.14763,1.884621,6.470884,NaN,NaN,5.632003,2.826049,30.599723,14.64575,324.0,8925.0,NaN,75.568347,0.133401,43.728642,16.117134

In [128]:
csv[2].loc[csv[2]["FIDC"] == fidc, cols_to_verify]

# Abr

,PL Total,PL Sênior,PL Subordinada Jr,Subordinação (%),Subordinação Jr (%),PDD Total (PL%),Vencidos Total (PL%),Prazo Médio,Taxa Média,Concentração Maior Cedente (PL%),Concentração Maior Sacado (PL%),Concentração 10 Maiores Cedentes (PL%),Concentração 10 Maiores Sacados (PL%),Quantidade de Cedentes,Quantidade de Sacados,Liquidados Total (PL%),Duplicata (PL%),Recompra (PL%),Volume Operado (PL%),Caixa/Disponibilidades (%PL)
19,9.666698e+08,5.515158e+08,3.029794e+08,42.946824,31.342592,1.626089,8.028664,NaN,NaN,5.105885,2.957832,31.654507,16.400306,314.0,7954.0,NaN,70.220883,0.292477,55.266482,15.180896