In [58]:
import pandas as pd

In [59]:
csv = []
for i in range(2, 5):
    csv.append(pd.read_csv(f'../data/GROUPED/FIDCS_2025_0{i}_01.csv', delimiter=';'))

len(csv)

3

In [60]:
cols_to_verify = ["PL Total", "PL Sênior", "PL Subordinada Jr", "Subordinação (%)",
                  "Subordinação Jr (%)", "PDD Total (PL%)", "CVNP (PL%)", "CVNP - PDD (PL%)",
                  "Prazo Médio", "Taxa Média", "Concentração Maior Cedente (PL%)",
                  "Concentração Maior Sacado (PL%)", "Concentração 10 Maiores Cedentes (PL%)",
                  "Concentração 10 Maiores Sacados (PL%)", "Quantidade de Cedentes",
                  "Quantidade de Sacados", "Liquidados Total (PL%)", "Duplicata (PL%)", "Duplicata (%)",
                  "Recompra (PL%)", "Volume Operado (PL%)", "Caixa/Disponibilidades (%PL)"]

In [61]:
fidc = "SABIA"

#Multiasset, sifraplus, sifrastars, barcelona em teoria, onix

In [62]:
csv[0].loc[csv[0]["FIDC"] == fidc, cols_to_verify]

# Fev

,PL Total,PL Sênior,PL Subordinada Jr,Subordinação (%),Subordinação Jr (%),PDD Total (PL%),CVNP (PL%),CVNP - PDD (PL%),Prazo Médio,Taxa Média,...,Concentração Maior Sacado (PL%),Concentração 10 Maiores Cedentes (PL%),Concentração 10 Maiores Sacados (PL%),Quantidade de Cedentes,Quantidade de Sacados,Liquidados Total (PL%),Duplicata (PL%),Recompra (PL%),Volume Operado (PL%),Caixa/Disponibilidades (%PL)
21,1.859019e+08,90009684.37,60707900.77,51.582154,32.655883,1.512796,9.946868,8.434072,57.273299,0.024285,...,2.969002,47.966548,23.439569,105.0,795.0,NaN,64.411734,3.98831,54.460443,1.211685

In [63]:
csv[1].loc[csv[1]["FIDC"] == fidc, cols_to_verify]

# Mar

,PL Total,PL Sênior,PL Subordinada Jr,Subordinação (%),Subordinação Jr (%),PDD Total (PL%),CVNP (PL%),CVNP - PDD (PL%),Prazo Médio,Taxa Média,...,Concentração Maior Sacado (PL%),Concentração 10 Maiores Cedentes (PL%),Concentração 10 Maiores Sacados (PL%),Quantidade de Cedentes,Quantidade de Sacados,Liquidados Total (PL%),Duplicata (PL%),Recompra (PL%),Volume Operado (PL%),Caixa/Disponibilidades (%PL)
20,1.907391e+08,93002733.61,62085710.75,51.240854,32.550078,1.627056,12.120377,10.493321,55.25164,0.022747,...,3.02,41.864396,21.410869,119.0,990.0,NaN,65.62841,3.770077,59.387222,1.759258

In [64]:
csv[2].loc[csv[2]["FIDC"] == fidc, cols_to_verify]

# Abr

Empty DataFrame
Columns: [PL Total, PL Sênior, PL Subordinada Jr, Subordinação (%), Subordinação Jr (%), PDD Total (PL%), CVNP (PL%), CVNP - PDD (PL%), Prazo Médio, Taxa Média, Concentração Maior Cedente (PL%), Concentração Maior Sacado (PL%), Concentração 10 Maiores Cedentes (PL%), Concentração 10 Maiores Sacados (PL%), Quantidade de Cedentes, Quantidade de Sacados, Liquidados Total (PL%), Duplicata (PL%), Recompra (PL%), Volume Operado (PL%), Caixa/Disponibilidades (%PL)]
Index: []

[0 rows x 21 columns]